import type * as Monaco from 'monaco-editor';

let registered = false;

export function registerCruxGardenThemes(monaco: typeof Monaco): void {
  if (registered) return;
  registered = true;

  monaco.editor.defineTheme('crux-garden-dark', {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '6a7a6e', fontStyle: 'italic' },
      { token: 'keyword', foreground: '7db3a3' },
      { token: 'keyword.control', foreground: '7db3a3' },
      { token: 'string', foreground: 'a8d4c4' },
      { token: 'string.escape', foreground: 'c4956a' },
      { token: 'number', foreground: 'c4956a' },
      { token: 'type', foreground: '9bc4b6' },
      { token: 'type.identifier', foreground: '9bc4b6' },
      { token: 'function', foreground: 'b8d8ca' },
      { token: 'variable', foreground: 'e2e4e3' },
      { token: 'variable.predefined', foreground: '9bc4b6' },
      { token: 'constant', foreground: 'c4956a' },
      { token: 'tag', foreground: '7db3a3' },
      { token: 'attribute.name', foreground: '9bc4b6' },
      { token: 'attribute.value', foreground: 'a8d4c4' },
      { token: 'delimiter', foreground: '8b908d' },
      { token: 'delimiter.bracket', foreground: '8b908d' },
      { token: 'operator', foreground: '8b908d' },
      { token: 'regexp', foreground: 'c4956a' },
      { token: 'annotation', foreground: '9bc4b6' },
      { token: 'meta', foreground: '6a7a6e' },
    ],
    colors: {
      'editor.background': '#0b0d0c',
      'editor.foreground': '#e2e4e3',
      'editor.lineHighlightBackground': '#15181712',
      'editor.selectionBackground': '#7db3a326',
      'editor.inactiveSelectionBackground': '#7db3a312',
      'editorCursor.foreground': '#7db3a3',
      'editorLineNumber.foreground': '#52605680',
      'editorLineNumber.activeForeground': '#8b908d',
      'editorIndentGuide.background': '#52605618',
      'editorIndentGuide.activeBackground': '#52605638',
      'editorWidget.background': '#131514',
      'editorWidget.border': '#52605630',
      'editor.wordHighlightBackground': '#7db3a312',
      'editorBracketMatch.background': '#7db3a320',
      'editorBracketMatch.border': '#7db3a340',
      'scrollbar.shadow': '#00000000',
      'scrollbarSlider.background': '#52605630',
      'scrollbarSlider.hoverBackground': '#8b908d50',
      'scrollbarSlider.activeBackground': '#8b908d70',
      'editorGutter.background': '#0b0d0c',
      'editorOverviewRuler.border': '#00000000',
      'minimap.background': '#0b0d0c',
      'input.background': '#131514',
      'input.border': '#52605630',
      'input.foreground': '#e2e4e3',
      focusBorder: '#7db3a350',
    },
  });

  monaco.editor.defineTheme('crux-garden-light', {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '616864', fontStyle: 'italic' },
      { token: 'keyword', foreground: '4a8074' },
      { token: 'string', foreground: '3a7060' },
      { token: 'number', foreground: '9a6840' },
      { token: 'type', foreground: '507a6e' },
      { token: 'function', foreground: '3a7060' },
      { token: 'variable', foreground: '1c211d' },
      { token: 'constant', foreground: '9a6840' },
      { token: 'tag', foreground: '4a8074' },
      { token: 'attribute.name', foreground: '507a6e' },
      { token: 'attribute.value', foreground: '3a7060' },
      { token: 'delimiter', foreground: '616864' },
      { token: 'operator', foreground: '616864' },
    ],
    colors: {
      'editor.background': '#eaeceb',
      'editor.foreground': '#1c211d',
      'editor.lineHighlightBackground': '#d8dad910',
      'editor.selectionBackground': '#4a80741f',
      'editor.inactiveSelectionBackground': '#4a80740f',
      'editorCursor.foreground': '#4a8074',
      'editorLineNumber.foreground': '#61686440',
      'editorLineNumber.activeForeground': '#616864',
      'editorIndentGuide.background': '#61686418',
      'editorWidget.background': '#e0e2e1',
      'scrollbar.shadow': '#00000000',
      'scrollbarSlider.background': '#61686420',
      'editorGutter.background': '#eaeceb',
      'editorOverviewRuler.border': '#00000000',
    },
  });
}
