
name: cruxgarden
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
