/**
 * AGENTS.md — "how to work here" for every agent (AI-COLLABORATION-V3 B1,
 * ADR 0013).
 *
 * One renderer, two readers: the file written into the Project Folder for an
 * external agent (Claude Code, Codex, Cursor…) and the built-in collaborator's
 * workspace context (`buildContextFromData` embeds the same sections). If they
 * ever disagreed, two agents would be working in two different cruxes.
 *
 * The file is deterministic for a given crux + persona — no timestamps, no
 * ids, no live file listing — so regeneration is cheap to compare and the
 * Growth history does not churn. It is a folder file: written through the
 * artifact service (so the watcher's echo is a no-op and the Artifacts panel
 * shows it), excluded from publish (`publish.ts`), regenerated whenever the
 * template, persona or crux instructions change.
 */

import type { Artifact, Crux } from '@/api/types';
import type { ContentModel, ContentCollection, FormField, BuilderAction } from '@/templates';
import type { PersonaSettings } from './persona';
import { isSiteCrux } from './site';
import { Capability, can } from '@/lib/platform';

export const AGENTS_MD_PATH = 'AGENTS.md';
export const CLAUDE_MD_PATH = 'CLAUDE.md';
export const CLAUDE_MD_CONTENT =
  'See AGENTS.md — it is generated by Crux Garden for every agent working in this folder.\n';

/** The generated guide files at the folder root (never published, never diffed as work). */
export function isGeneratedGuidePath(path: string): boolean {
  return path === AGENTS_MD_PATH || path === CLAUDE_MD_PATH;
}

// ── Input ───────────────────────────────────────────────────────────────────

export interface AgentsMdInput {
  crux: Pick<Crux, 'title' | 'kind' | 'meta'>;
  artifacts: Pick<Artifact, 'type' | 'meta' | 'filename'>[];
  persona: Pick<PersonaSettings, 'name' | 'systemPrompt'>;
  /** Whether `check_site` (a real build) is available where this file is read. */
  canBuild?: boolean;
}

export interface AgentsMdSections {
  about: string;
  contentModel: string | null;
  conventions: string;
  preview: string;
  handsOff: string;
  recording: string;
  voice: string;
  instructions: string | null;
}

/** Pretty name for a template id: "astro-blog" → "Astro Blog". */
export function templateDisplayName(id: string): string {
  return id
    .split(/[-_]/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

// ── Sections ────────────────────────────────────────────────────────────────

export function renderAgentsMdSections(input: AgentsMdInput): AgentsMdSections {
  const meta = (input.crux.meta ?? {}) as Record<string, unknown>;
  const settings = (meta.settings ?? {}) as Record<string, unknown>;
  const site = isSiteCrux(input.artifacts);
  const contentModel = meta.contentModel as ContentModel | undefined;
  const templateId = typeof meta.template === 'string' ? meta.template : null;
  const canBuild = input.canBuild ?? false;

  return {
    about: renderAbout(input.crux, site, templateId),
    contentModel: contentModel ? renderContentModel(contentModel) : null,
    conventions: renderConventions(site, contentModel),
    preview: renderPreview(site, canBuild),
    handsOff: renderHandsOff(site),
    recording: RECORDING,
    voice: renderVoice(input.persona),
    instructions:
      typeof settings.systemPrompt === 'string' && settings.systemPrompt.trim()
        ? '## Instructions for this crux\n' + settings.systemPrompt.trim()
        : null,
  };
}

function renderAbout(
  crux: Pick<Crux, 'title' | 'kind'>,
  site: boolean,
  templateId: string | null,
): string {
  const lines = ['## About this crux'];
  lines.push(`- Title: ${crux.title || 'Untitled'}`);
  lines.push(
    `- Kind: ${site ? 'Site Crux (a real toolchain project with a build step)' : describeKind(crux.kind)}`,
  );
  if (templateId) lines.push(`- Template: ${templateDisplayName(templateId)} (\`${templateId}\`)`);
  lines.push(
    '',
    'This folder is a Crux — a creative project in Crux Garden: a conversation with an AI plus the files it produces, with every version kept as Growth history. ' +
      'The folder is the truth: whatever you write here is what the crux is. Edits are ingested into history automatically.',
  );
  return lines.join('\n');
}

function describeKind(kind: string | undefined): string {
  switch (kind) {
    case 'webapp':
      return 'web app (browser-native, served as written — no build step)';
    case 'page':
      return 'page (static HTML, served as written)';
    case 'document':
      return 'document (writing)';
    case 'image':
      return 'image';
    case 'notes':
      return 'notes';
    case 'mood':
      return 'Mood (a theme + soundscape package)';
    default:
      return 'general (files served as written — no build step)';
  }
}

function renderConventions(site: boolean, model: ContentModel | undefined): string {
  const lines = ['## Files and folder layout'];
  if (site) {
    lines.push(
      '- Source lives in `src/`: pages in `src/pages` (file-based routing — `index.astro` is `/`), layouts in `src/layouts`, styles in `src/styles`, components in `src/components`.',
      '- Static assets (favicon, images, media) go in `public/` and are served from `/`.',
      '- Dependencies go in `package.json`; the app runs `pnpm install` for you.',
      '- Write real `.astro`, `.md`, `.ts` files — the toolchain compiles them. No CDN import maps or `React.createElement` workarounds here.',
      '- Markdown content needs correct frontmatter; follow the Content Model exactly so the Builder and the files agree.',
    );
  } else {
    lines.push(
      '- Files are served to the browser exactly as written: plain HTML, CSS and browser-native ES modules (`.js`, not TypeScript/JSX).',
      '- Reference other files with relative paths (`./styles.css`, `./app.js`); never absolute URLs into the workspace.',
      '- External packages come from an import map pointing at `https://esm.sh/<package>@<version>`.',
      '- Keep directories clear: `components/`, `lib/`, `assets/`.',
    );
  }
  lines.push('- Paths are relative to this folder, forward slashes, no leading `/`.');
  if (model?.settings) {
    lines.push(
      `- \`${model.settings.path}\` is edited by the person as a form — keep it valid JSON with exactly its keys.`,
    );
  }
  for (const c of model?.collections ?? []) {
    lines.push(
      `- ${c.name} are \`${c.glob}\`${c.routeBase ? ` (served at \`${c.routeBase}\`)` : ''}.`,
    );
  }
  return lines.join('\n');
}

function renderPreview(site: boolean, canBuild: boolean): string {
  const lines = ['## Preview and verification'];
  if (site) {
    lines.push(
      '- Preview: Crux Garden runs `astro dev` in this folder with hot reload; `pnpm dev` works in a terminal too.',
      '- Publish runs the production build and ships `dist/` — a broken build blocks publishing. Keep the project building; prefer small, verifiable changes.',
    );
    lines.push(
      canBuild
        ? '- `check_site` runs the production build without publishing. Run it after changes that could break the build (config, layouts, frontmatter, dependencies) and fix what it reports before saying you are done.'
        : '- Verify with `pnpm build` after changes that could break the build (config, layouts, frontmatter, dependencies) and fix what it reports before saying you are done.',
    );
  } else {
    lines.push(
      '- Preview: the app serves this folder as a static site; `index.html` is the front page.',
      '- Nothing is built. If it works when the files are opened as-is, it works published.',
    );
  }
  return lines.join('\n');
}

function renderHandsOff(site: boolean): string {
  const lines = [
    '## Never touch',
    '- `.crux/` — Crux Garden state (the agent-host token lives here). Not yours to edit.',
    '- `_crux/` — reserved for the published site (`_crux/cover.jpg`).',
    '- `AGENTS.md` and `CLAUDE.md` — generated; edit the persona or the crux instructions in the app instead, and they regenerate.',
    '- `preview.jpg` — the crux thumbnail, re-shot by the app.',
  ];
  if (site)
    lines.push('- `node_modules/`, `dist/`, `.astro/` — build machinery managed by the app.');
  lines.push(
    '- History (published versions, Growth snapshots) lives in Crux Garden, not in this folder. Do not try to recreate or edit old versions as files — use snapshots.',
  );
  return lines.join('\n');
}

const RECORDING = [
  '## Recording work (Growth)',
  'Growth is the version history: every snapshot holds every file plus the conversation so far, and the timeline shows who took it.',
  '- `snapshot(label?)` — record a checkpoint. Take one before a risky or multi-file change and after finishing a coherent piece of work.',
  '- `list_snapshots(limit?)` — ids, labels, summaries.',
  '- `restore(snapshotId)` — put the files back to a snapshot (a safety snapshot of the current state is taken first). Use it when a check fails and going back beats fixing forward.',
  '- `branch(snapshotId, label)` — try a different direction from an earlier version without losing the current one.',
  '- `diff(from, to?)` — files added/removed/modified between two snapshots, or against the working files.',
  'The app also snapshots automatically after a turn that changed files. Agents connected through Crux Garden (the built-in collaborator, or an MCP client once the crux is enabled as an agent host) have these as tools; edits made any other way are still recorded by the automatic history.',
].join('\n');

function renderVoice(persona: Pick<PersonaSettings, 'name' | 'systemPrompt'>): string {
  const lines = ['## Voice', `The collaborator here is **${persona.name || 'The Keeper'}**.`];
  if (persona.systemPrompt?.trim()) lines.push('', persona.systemPrompt.trim());
  return lines.join('\n');
}

// ── Content model (shared with the system prompt) ───────────────────────────

/**
 * Render the crux's content model (crux.meta.contentModel — the declaration
 * the Builder UI is generated from) so chat-created content matches what the
 * Builder produces: same paths, same frontmatter, same settings shape.
 */
export function renderContentModel(model: ContentModel): string {
  const lines: string[] = [
    '## Content Model',
    'This crux has a Builder UI generated from the content model below. When creating or editing content, follow it exactly so your files and the Builder agree.',
  ];

  for (const collection of model.collections ?? []) {
    lines.push('', ...renderCollection(collection));
  }

  if (model.settings) {
    lines.push(
      '',
      `### Settings file: ${model.settings.path}`,
      `Fields: ${fieldSummary(model.settings.fields)}`,
      'The user edits this file as a form — keep it valid JSON with exactly these keys.',
    );
  }

  const actions = builderActions(model);
  if (actions.length > 0) {
    lines.push(
      '',
      '### Builder actions',
      'The person has these buttons in the Builder; when they ask for the same thing in words, produce the same files:',
      ...actions.map((a) => `- ${a}`),
    );
  }

  return lines.join('\n');
}

function renderCollection(collection: ContentCollection): string[] {
  const lines: string[] = [
    `### Collection: ${collection.name} (singular "${collection.singular}")`,
    `- Files: ${collection.glob}${collection.routeBase ? ` — served at ${collection.routeBase}` : ''}`,
    `- Frontmatter fields: ${fieldSummary(collection.fields)}`,
  ];

  if (collection.new) {
    lines.push(
      `- New ${collection.singular} recipe — create ${collection.new.pathTemplate} ` +
        "(placeholders: {slug} = kebab-case of the title, {title} = the title, {today} = today's date as YYYY-MM-DD) " +
        'with this frontmatter:',
      '```yaml',
      ...Object.entries(collection.new.frontmatter).map(([key, value]) => `${key}: ${value}`),
      '```',
    );
  }

  if (collection.sort) {
    lines.push(
      `- Listed in ${collection.sort.dir === 'desc' ? 'descending' : 'ascending'} order by "${collection.sort.field}".`,
    );
  }

  return lines;
}

function fieldSummary(fields: FormField[]): string {
  return fields.map((f) => `${f.key} ("${f.label}")`).join(', ');
}

/** The Builder's buttons as the model sees them: derived from the collections, plus the template's own. */
function builderActions(model: ContentModel): string[] {
  const out: string[] = [];
  for (const c of model.collections ?? []) {
    out.push(`New ${c.singular} — creates ${c.new.pathTemplate} from the recipe above.`);
  }
  if (model.settings) out.push(`Settings — edits ${model.settings.path} as a form.`);
  for (const a of model.actions ?? []) out.push(describeAction(a));
  return out;
}

function describeAction(a: BuilderAction): string {
  switch (a.do.type) {
    case 'new-item':
      return `${a.label} — a new item in the "${a.do.collection}" collection.`;
    case 'edit-settings':
      return `${a.label} — edits the settings file.`;
    case 'open-file':
      return `${a.label} — opens ${a.do.path}.`;
    case 'add-image':
      return `${a.label} — uploads an image into the workspace.`;
    case 'add-media':
      return `${a.label} — uploads audio/video into public/media/ (transcoding when needed) and writes an item in "${a.do.collection}".`;
    case 'add-photos':
      return `${a.label} — uploads images into public/images/ and writes one item per image in "${a.do.collection}" (its image field).`;
    case 'publish':
      return `${a.label} — publishes the crux.`;
  }
}

// ── Assembly ────────────────────────────────────────────────────────────────

const HEADER =
  '# AGENTS.md\n\n' +
  'Generated by Crux Garden for any agent working in this folder — the built-in collaborator reads the same guidance. ' +
  'Do not edit: it is regenerated when the crux, its template, its instructions or the persona change.';

/**
 * The parts every agent needs about the workspace itself (everything except
 * the persona's voice and the crux's instructions, which the built-in
 * collaborator already carries in its stable system prompt).
 */
export function renderWorkspaceGuide(input: AgentsMdInput): string {
  const s = renderAgentsMdSections(input);
  return [s.about, s.contentModel, s.conventions, s.preview, s.handsOff, s.recording]
    .filter((x): x is string => !!x)
    .join('\n\n');
}

/** The full file. */
export function renderAgentsMd(input: AgentsMdInput): string {
  const s = renderAgentsMdSections(input);
  return (
    [HEADER, renderWorkspaceGuide(input), s.voice, s.instructions]
      .filter((x): x is string => !!x)
      .join('\n\n') + '\n'
  );
}

// ── Writing it into the Project Folder ──────────────────────────────────────

export interface AgentsMdWriterDeps {
  /** Whether the guide files should exist at all — Desktop Mode (a Project Folder) by default. */
  enabled: () => boolean;
  persona: () => Pick<PersonaSettings, 'name' | 'systemPrompt'>;
  canBuild: () => boolean;
  artifact: {
    findByResource(resourceType: string, resourceId: string): Promise<Artifact[]>;
    create(input: {
      resourceId: string;
      content: string;
      mimeType?: string;
      meta?: { path?: string };
    }): Promise<unknown>;
  };
  hash: (content: string) => Promise<string>;
}

/** Fill in whatever the caller did not inject; `enabled` is decided before anything is imported. */
async function resolveWriterDeps(
  partial: Partial<AgentsMdWriterDeps> | undefined,
): Promise<AgentsMdWriterDeps | null> {
  const d: Partial<AgentsMdWriterDeps> = { ...partial };
  d.enabled ??= () => can(Capability.ProjectFolder);
  if (!d.enabled()) return null;
  d.canBuild ??= () => can(Capability.Build);
  if (!d.persona) d.persona = (await import('./persona')).getPersona;
  if (!d.hash) d.hash = (await import('./sqlite/helpers')).hashContent;
  if (!d.artifact) d.artifact = (await import('./index')).getServices().artifact;
  return d as AgentsMdWriterDeps;
}

/**
 * Bring `AGENTS.md` (and the one-line `CLAUDE.md`) in the crux up to date
 * with what the renderer says now. Compares by content fingerprint against
 * the existing artifact, so a no-change call costs one hash and no write.
 * Returns true when a file was (re)written. Never throws — the guide is a
 * convenience, and a failure here must not fail the create/turn it rides on.
 */
export async function syncAgentsMd(
  crux: Crux,
  artifacts: Artifact[] | null,
  deps?: Partial<AgentsMdWriterDeps>,
): Promise<boolean> {
  const d = await resolveWriterDeps(deps);
  if (!d) return false;
  try {
    const current = artifacts ?? (await d.artifact.findByResource('crux', crux.id));
    const rendered = renderAgentsMd({
      crux,
      artifacts: current,
      persona: d.persona(),
      canBuild: d.canBuild(),
    });
    let wrote = false;
    for (const [path, content] of [
      [AGENTS_MD_PATH, rendered],
      [CLAUDE_MD_PATH, CLAUDE_MD_CONTENT],
    ] as const) {
      const existing = current.find(
        (a) => a.type === 'artifact' && (a.meta?.path || a.filename) === path,
      );
      if (existing?.fingerprint && existing.fingerprint === (await d.hash(content))) continue;
      await d.artifact.create({
        resourceId: crux.id,
        content,
        mimeType: 'text/markdown',
        meta: { path },
      });
      wrote = true;
    }
    return wrote;
  } catch (err) {
    console.warn('[agents-md] could not write the guide:', err);
    return false;
  }
}

/**
 * Service-backed convenience for UI hooks: call after the persona or a
 * crux's instructions are saved so the folder's guide follows.
 */
export async function refreshAgentsMd(cruxId: string): Promise<boolean> {
  const { getServices } = await import('./index');
  const { crux: cruxService } = getServices();
  const crux = await cruxService.findById(cruxId);
  return syncAgentsMd(crux, null);
}
