/**
 * Mood Presets — 30 curated palettes (15 dark, 15 light)
 *
 * Each preset is a set of CSS variable overrides layered on Garden Dark.
 * They vary in: shade, structure, saturation, warmth, contrast, and vibe.
 */

export interface MoodPresetDef {
  id: string;
  name: string;
  section: 'Dark' | 'Light';
  overrides: Record<string, string>;
}

// Helper: "ghost" style — transparent header, no borders, just tinted text
function ghostPanes(panes: Record<string, string>, headerBg: string, closeMuted: string) {
  const result: Record<string, string> = {};
  for (const [key, color] of Object.entries(panes)) {
    const prefix = key;
    result[`${prefix}Header`] = headerBg;
    result[`${prefix}HeaderBorder`] = 'transparent';
    result[`${prefix}HeaderText`] = color;
    result[`${prefix}HeaderIcon`] = color;
    result[`${prefix}HeaderClose`] = closeMuted;
    result[`${prefix}ButtonActive`] = headerBg;
    result[`${prefix}ButtonIconActive`] = color;
    result[`${prefix}ButtonBorderActive`] = 'transparent';
  }
  return result;
}

// Syntax colors for light backgrounds — dark saturated tones with good contrast
// Light syntax colors use var() references so they follow the mood's palette
const LIGHT_SYNTAX = {
  syntaxComment: 'var(--text-muted)',
  syntaxKeyword: 'var(--accent)',
  syntaxString: 'var(--pane-details)', // green pane
  syntaxNumber: 'var(--pane-artifacts)', // orange pane
  syntaxType: 'var(--pane-export)', // blue pane
  syntaxFunction: 'var(--pane-workshop)', // gold pane
  syntaxPunctuation: 'var(--text-muted)',
  syntaxVariable: 'var(--pane-history)', // teal pane
  syntaxTag: 'var(--pane-collaboration)', // rose pane
  syntaxAttribute: 'var(--pane-workshop)', // gold pane
};

// Blade Runner helper: each pane gets a two-tone neon gradient frame, a black
// header with the neon as text, and a slightly lifted body.
function neonFrames(panes: Record<string, [string, string]>) {
  const result: Record<string, string> = {};
  for (const [key, [neon, deep]] of Object.entries(panes)) {
    result[`${key}Border`] = `linear-gradient(160deg, ${neon}, ${deep} 60%, ${neon})`;
    result[`${key}Body`] = '#0a0d1a';
    result[`${key}Surface`] = '#10142a';
    result[`${key}Header`] = '#04050d';
    result[`${key}HeaderBorder`] = 'transparent';
    result[`${key}HeaderText`] = neon;
    result[`${key}HeaderIcon`] = neon;
    result[`${key}HeaderClose`] = deep;
    result[`${key}Caption`] = neon;
    result[`${key}Heading`] = '#ffb86b';
    result[`${key}Accent`] = neon;
    result[`${key}ButtonActive`] = `color-mix(in srgb, ${neon} 18%, transparent)`;
    result[`${key}ButtonBorderActive`] = neon;
  }
  return result;
}

// Windows 95 helper: every pane is the same grey window — a raised bevel
// (light top-left, dark bottom-right, done with a hard diagonal gradient on
// the frame), a navy title bar with white text, and no radius anywhere.
function win95Panes(keys: string[]) {
  const result: Record<string, string> = {};
  for (const key of keys) {
    result[key] = '#000080';
    result[`${key}Body`] = '#c0c0c0';
    result[`${key}Surface`] = '#dfdfdf';
    result[`${key}SurfaceSolid`] = '#c0c0c0';
    result[`${key}Border`] = 'linear-gradient(135deg, #ffffff 0 50%, #404040 50%)';
    result[`${key}Header`] = 'linear-gradient(90deg, #000080, #1084d0)';
    result[`${key}HeaderBorder`] = 'transparent';
    result[`${key}HeaderText`] = '#ffffff';
    result[`${key}HeaderIcon`] = '#ffffff';
    result[`${key}HeaderClose`] = '#ffffff';
    result[`${key}HeaderRadius`] = '0px';
    result[`${key}HeaderHeight`] = '22px';
    result[`${key}Radius`] = '0px';
    result[`${key}RadiusSm`] = '0px';
    result[`${key}Text`] = '#000000';
    result[`${key}TextMuted`] = '#3a3a3a';
    result[`${key}Caption`] = '#000080';
    result[`${key}Heading`] = '#000000';
    result[`${key}Accent`] = '#000080';
    result[`${key}AccentMuted`] = '#b8b8d8';
    result[`${key}Button`] = '#000080';
    result[`${key}ButtonIcon`] = '#000080';
    result[`${key}ButtonActive`] = '#ffffff';
    result[`${key}ButtonBorderActive`] = '#808080';
  }
  return result;
}

// ── Shared anatomy for the explorations below ─────────────────────────────
const ALL_PANES = [
  'paneCollaboration',
  'paneArtifacts',
  'paneWorkshop',
  'paneDetails',
  'paneHistory',
  'paneExport',
  'paneSync',
  'panePublish',
  'paneStore',
];

/** The same body/frame/header for every pane (uniform looks). */
function uniformPanes(t: {
  body: string;
  surface?: string;
  border: string;
  header: string;
  headerText: string;
  headerBorder?: string;
  text?: string;
  textMuted?: string;
  caption?: string;
  heading?: string;
  accent?: string;
  radius?: string;
  headerRadius?: string;
  headerHeight?: string;
  borderWidth?: string;
}) {
  const result: Record<string, string> = {};
  for (const key of ALL_PANES) {
    result[`${key}Body`] = t.body;
    if (t.surface) result[`${key}Surface`] = t.surface;
    result[`${key}Border`] = t.border;
    result[`${key}Header`] = t.header;
    result[`${key}HeaderBorder`] = t.headerBorder ?? 'transparent';
    result[`${key}HeaderText`] = t.headerText;
    result[`${key}HeaderIcon`] = t.headerText;
    result[`${key}HeaderClose`] = t.headerText;
    if (t.text) result[`${key}Text`] = t.text;
    if (t.textMuted) result[`${key}TextMuted`] = t.textMuted;
    if (t.caption) result[`${key}Caption`] = t.caption;
    if (t.heading) result[`${key}Heading`] = t.heading;
    if (t.accent) result[`${key}Accent`] = t.accent;
    if (t.radius) result[`${key}Radius`] = t.radius;
    if (t.headerRadius) result[`${key}HeaderRadius`] = t.headerRadius;
    if (t.headerHeight) result[`${key}HeaderHeight`] = t.headerHeight;
    if (t.borderWidth) result[`${key}BorderWidth`] = t.borderWidth;
  }
  return result;
}

/** Each pane its own header tint from a list (pastel looks). */
function tintedHeaders(tints: string[], text: string) {
  const result: Record<string, string> = {};
  ALL_PANES.forEach((key, i) => {
    const tint = tints[i % tints.length]!;
    result[key] = tint;
    result[`${key}Header`] = tint;
    result[`${key}HeaderBorder`] = 'transparent';
    result[`${key}HeaderText`] = text;
    result[`${key}HeaderIcon`] = text;
    result[`${key}HeaderClose`] = text;
    result[`${key}Caption`] = tint;
    result[`${key}ButtonIcon`] = tint;
    result[`${key}ButtonActive`] = `color-mix(in srgb, ${tint} 25%, transparent)`;
  });
  return result;
}

const NO_BLOOM = {
  bloom1: 'transparent',
  bloom2: 'transparent',
  bloom3: 'transparent',
  bloom4: 'transparent',
  bloom5: 'transparent',
  bloom6: 'transparent',
  bloomOpacity: '0',
};

export const MOOD_PRESETS: MoodPresetDef[] = [
  // ── Lofi Café — warm cream, big soft radii, paper grain, chunky friendly type ──
  {
    id: 'lofi-cafe',
    name: 'Lofi Café',
    section: 'Light',
    overrides: {
      bg: '#f3e9dc',
      panel: '#fbf5ec',
      surface: '#efe3d3',
      surfaceSolid: '#fbf5ec',
      accent: '#b0563a',
      accentMuted: '#f1d9cb',
      border: '#e2d2bf',
      text: '#3b2e25',
      textMuted: '#8a7462',
      heading: '#2b211b',
      caption: '#a4785e',
      highlight: '#d99a5b',
      error: '#b64a3e',
      warning: '#c58a2b',
      success: '#5d8a5a',
      radius: '1.25rem',
      radiusSm: '0.875rem',
      radiusLg: '1.75rem',
      buttonRadius: '9999px',
      inputRadius: '9999px',
      chipRadius: '9999px',
      bubbleRadius: '1.25rem',
      cardRadius: '1.5rem',
      paneRadius: '1.5rem',
      paneHeaderRadius: '1.5rem',
      paneGap: '14px',
      workspacePadding: '14px',
      paneBorderWidth: '0px',
      paneHeaderHeight: '40px',
      paneHeaderLabelCase: 'none',
      paneHeaderLabelFont: "'Outfit', sans-serif",
      paneHeaderLabelSize: '13px',
      paneHeaderLabelWeight: '600',
      paneHeaderLabelTracking: '0',
      paneHeaderJustify: 'flex-start',
      paneHeaderIconDisplay: 'none',
      fontDisplay: "'Outfit', sans-serif",
      fontBody: "'Outfit', sans-serif",
      fontScale: '1.05',
      density: '1.1',
      motionScale: '1.4',
      grainOpacity: '0.08',
      elevationPanel: '0 18px 40px -22px rgb(80 50 20 / 0.25)',
      elevationCard: '0 10px 30px -18px rgb(80 50 20 / 0.25)',
      elevationCardHover: '0 22px 40px -18px rgb(80 50 20 / 0.32)',
      elevationDropdown: '0 18px 40px -16px rgb(80 50 20 / 0.35)',
      cardHoverLift: '4px',
      focusRing: '#d99a5b',
      focusRingWidth: '3px',
      toolbar: '#f3e9dc',
      toolbarText: '#3b2e25',
      toolbarTextMuted: '#8a7462',
      toolbarBorder: 'transparent',
      toolbarDivider: '#e2d2bf',
      toolbarHeight: '56px',
      iconButtonIcon: '#8a7462',
      iconButtonIconHover: '#b0563a',
      iconButtonHover: '#efe3d3',
      moodBar: '#fbf5ec',
      moodBarBorder: '#e2d2bf',
      moodBarAccent: '#b0563a',
      moodBarAccentText: '#fbf5ec',
      chat: '#fbf5ec',
      chatUserBubble: '#b0563a',
      chatUserBubbleText: '#fbf5ec',
      chatUserBubbleBorder: '#b0563a',
      chatAiBubble: '#f3e9dc',
      chatAiText: '#3b2e25',
      chatAiBubbleBorder: '#e2d2bf',
      chatInput: '#fbf5ec',
      chatInputBorder: '#e2d2bf',
      chatInputBorderFocus: '#d99a5b',
      chatSendButton: '#b0563a',
      chatSendButtonHover: '#c4674a',
      chatSendButtonIcon: '#fbf5ec',
      primaryButton: '#b0563a',
      primaryButtonText: '#fbf5ec',
      primaryButtonBorder: '#b0563a',
      primaryButtonHover: '#c4674a',
      actionButton: '#efe3d3',
      actionButtonText: '#3b2e25',
      actionButtonBorder: 'transparent',
      actionButtonHover: '#e6d5c1',
      badge: '#f1d9cb',
      badgeText: '#b0563a',
      badgeBorder: 'transparent',
      gardenCard: '#fbf5ec',
      gardenCardBorder: 'transparent',
      gardenCardBorderHover: '#d99a5b',
      gardenCardThumbnail: '#efe3d3',
      gardenCardAspect: '4 / 3',
      gardenCardMinWidth: '260px',
      fileTreeItemSelected: '#f1d9cb',
      fileTreeItemTextSelected: '#b0563a',
      fileTreeItemHover: '#efe3d3',
      editorBackground: '#fbf5ec',
      // Panes: every pane the same warm paper, the header a soft cream cap
      paneCollaboration: '#b0563a',
      paneArtifacts: '#c58a2b',
      paneWorkshop: '#5d8a5a',
      paneDetails: '#6d8fb0',
      paneHistory: '#9a6fb0',
      paneExport: '#5c9aa6',
      paneSync: '#8a7462',
      panePublish: '#b0563a',
      paneStore: '#6d8fb0',
      bloomBg1: '#f3e9dc',
      bloomBg2: '#e9d9c4',
      bloom1: '#f1d9cb',
      bloom2: '#efe3d3',
      bloom3: '#e5cdb2',
      bloom4: '#f5e1d2',
      bloom5: '#e9d9c4',
      bloom6: '#f3e9dc',
      bloomOpacity: '0.9',
      bloomSpeed: '0.4',
    },
  },
  // ── Solarpunk Garden — deep greens, gold, leaf textures, generous rounded glass ──
  {
    id: 'solarpunk-garden',
    name: 'Solarpunk Garden',
    section: 'Dark',
    overrides: {
      bg: '#0b1a12',
      panel: 'color-mix(in srgb, #12291c 78%, transparent)',
      surface: '#173424',
      surfaceSolid: '#12291c',
      accent: '#e2b743',
      accentMuted: '#2c3a1c',
      border: '#26493a',
      text: '#e9f2e6',
      textMuted: '#8fb39a',
      heading: '#f4e6b8',
      caption: '#7fc39a',
      highlight: '#e2b743',
      error: '#e06c5b',
      warning: '#e2b743',
      success: '#7fd39a',
      radius: '1rem',
      radiusSm: '0.625rem',
      radiusLg: '1.5rem',
      paneRadius: '1.25rem',
      paneHeaderRadius: '1.25rem',
      paneGap: '12px',
      workspacePadding: '12px',
      paneBorderWidth: '1px',
      paneHeaderHeight: '34px',
      paneHeaderLabelCase: 'lowercase',
      paneHeaderLabelFont: "'Cormorant Garamond', Georgia, serif",
      paneHeaderLabelSize: '15px',
      paneHeaderLabelWeight: '600',
      paneHeaderLabelTracking: '0.02em',
      fontDisplay: "'Cormorant Garamond', Georgia, serif",
      fontBody: "'Outfit', sans-serif",
      fontScale: '1.02',
      glassBlur: '18px',
      grainOpacity: '0.05',
      workspaceTexture:
        'radial-gradient(ellipse at 20% 10%, rgb(226 183 67 / 0.08), transparent 45%), radial-gradient(ellipse at 80% 90%, rgb(127 211 154 / 0.10), transparent 50%)',
      elevationPanel: '0 20px 60px -30px rgb(0 0 0 / 0.6), inset 0 1px 0 rgb(255 255 255 / 0.06)',
      elevationCard: '0 10px 30px -18px rgb(0 0 0 / 0.6)',
      elevationCardHover: '0 20px 50px -20px rgb(226 183 67 / 0.25)',
      cardHoverLift: '3px',
      toolbar: 'color-mix(in srgb, #0b1a12 70%, transparent)',
      toolbarText: '#f4e6b8',
      toolbarTextMuted: '#8fb39a',
      toolbarBorder: '#26493a',
      toolbarDivider: '#26493a',
      iconButtonIcon: '#8fb39a',
      iconButtonIconHover: '#e2b743',
      iconButtonHover: '#173424',
      moodBar: '#12291c',
      moodBarBorder: '#26493a',
      moodBarAccent: '#e2b743',
      moodBarAccentText: '#0b1a12',
      chat: 'transparent',
      chatUserBubble: '#2c3a1c',
      chatUserBubbleText: '#f4e6b8',
      chatUserBubbleBorder: '#e2b743',
      chatAiBubble: '#173424',
      chatAiText: '#e9f2e6',
      chatAiBubbleBorder: '#26493a',
      chatInput: '#0f2117',
      chatInputBorder: '#26493a',
      chatInputBorderFocus: '#e2b743',
      chatSendButton: '#e2b743',
      chatSendButtonHover: '#f0c85a',
      chatSendButtonIcon: '#0b1a12',
      primaryButton: '#e2b743',
      primaryButtonText: '#0b1a12',
      primaryButtonBorder: '#e2b743',
      primaryButtonHover: '#f0c85a',
      actionButton: '#173424',
      actionButtonText: '#e9f2e6',
      actionButtonBorder: '#26493a',
      actionButtonHover: '#1e4430',
      badge: '#1e4430',
      badgeText: '#7fd39a',
      badgeBorder: '#26493a',
      gardenCard: '#12291c',
      gardenCardBorder: '#26493a',
      gardenCardBorderHover: '#e2b743',
      gardenCardThumbnail: '#0f2117',
      gardenCardAspect: '1 / 1',
      fileTreeItemSelected: '#2c3a1c',
      fileTreeItemTextSelected: '#f4e6b8',
      fileTreeItemHover: '#173424',
      editorBackground: '#0f2117',
      syntaxKeyword: '#e2b743',
      syntaxString: '#7fd39a',
      syntaxFunction: '#8fc9ff',
      syntaxComment: '#5f8a6d',
      paneCollaboration: '#e2b743',
      paneArtifacts: '#7fd39a',
      paneWorkshop: '#8fc9ff',
      paneDetails: '#f4e6b8',
      paneHistory: '#c9a5e8',
      paneExport: '#7fc39a',
      paneSync: '#8fb39a',
      panePublish: '#e2b743',
      paneStore: '#8fc9ff',
      bloomBg1: '#0b1a12',
      bloomBg2: '#12291c',
      bloom1: '#1e4430',
      bloom2: '#2c3a1c',
      bloom3: '#173424',
      bloom4: '#3a5a2a',
      bloom5: '#26493a',
      bloom6: '#0f2117',
      bloomOpacity: '0.8',
      bloomSpeed: '0.5',
    },
  },
  // ── Sunday Paper — off-white pages, hairline rules, serif display, no radii, wide gutters ──
  {
    id: 'sunday-paper',
    name: 'Sunday Paper',
    section: 'Light',
    overrides: {
      bg: '#f7f5f0',
      panel: '#fdfcf9',
      surface: '#f1eee7',
      surfaceSolid: '#fdfcf9',
      accent: '#9b2226',
      accentMuted: '#f3e4e2',
      border: '#1a1a1a',
      text: '#1a1a1a',
      textMuted: '#6b6560',
      heading: '#1a1a1a',
      caption: '#6b6560',
      highlight: '#9b2226',
      error: '#9b2226',
      warning: '#8a6d1f',
      success: '#3d6b45',
      radius: '0px',
      radiusSm: '0px',
      radiusLg: '0px',
      buttonRadius: '0px',
      inputRadius: '0px',
      chipRadius: '0px',
      cardRadius: '0px',
      modalRadius: '0px',
      tooltipRadius: '0px',
      dropdownRadius: '0px',
      bubbleRadius: '0px',
      paneRadius: '0px',
      paneHeaderRadius: '0px',
      paneGap: '28px',
      workspacePadding: '28px',
      paneBorderWidth: '1px',
      paneHeaderHeight: '36px',
      paneHeaderLabelCase: 'uppercase',
      paneHeaderLabelFont: "'Cormorant Garamond', Georgia, serif",
      paneHeaderLabelSize: '13px',
      paneHeaderLabelWeight: '700',
      paneHeaderLabelTracking: '0.18em',
      paneHeaderJustify: 'center',
      paneHeaderIconDisplay: 'none',
      fontDisplay: "'Cormorant Garamond', Georgia, serif",
      fontBody: "Georgia, 'Times New Roman', serif",
      fontMono: "'JetBrains Mono', monospace",
      fontScale: '1.06',
      lineHeightBody: '1.65',
      density: '1.15',
      motionScale: '0.6',
      elevationPanel: 'none',
      elevationCard: 'none',
      elevationCardHover: 'none',
      elevationModal: '0 0 0 1px #1a1a1a',
      elevationDropdown: '0 0 0 1px #1a1a1a',
      elevationTooltip: '0 0 0 1px #1a1a1a',
      cardHoverLift: '0px',
      focusRing: '#9b2226',
      focusRingWidth: '2px',
      toolbar: '#f7f5f0',
      toolbarText: '#1a1a1a',
      toolbarTextMuted: '#6b6560',
      toolbarBorder: '#1a1a1a',
      toolbarDivider: '#1a1a1a',
      toolbarHeight: '52px',
      iconButtonIcon: '#1a1a1a',
      iconButtonIconHover: '#9b2226',
      iconButtonHover: '#f1eee7',
      moodBar: '#fdfcf9',
      moodBarBorder: '#1a1a1a',
      moodBarAccent: '#9b2226',
      moodBarAccentText: '#fdfcf9',
      moodBarRadius: '0px',
      chat: '#fdfcf9',
      chatUserBubble: '#f1eee7',
      chatUserBubbleText: '#1a1a1a',
      chatUserBubbleBorder: '#1a1a1a',
      chatAiBubble: '#fdfcf9',
      chatAiText: '#1a1a1a',
      chatAiBubbleBorder: '#d8d2c8',
      chatInput: '#fdfcf9',
      chatInputBorder: '#1a1a1a',
      chatInputBorderFocus: '#9b2226',
      chatSendButton: '#1a1a1a',
      chatSendButtonHover: '#9b2226',
      chatSendButtonIcon: '#fdfcf9',
      primaryButton: '#1a1a1a',
      primaryButtonText: '#fdfcf9',
      primaryButtonBorder: '#1a1a1a',
      primaryButtonHover: '#9b2226',
      actionButton: '#fdfcf9',
      actionButtonText: '#1a1a1a',
      actionButtonBorder: '#1a1a1a',
      actionButtonHover: '#f1eee7',
      badge: '#fdfcf9',
      badgeText: '#9b2226',
      badgeBorder: '#9b2226',
      gardenCard: '#fdfcf9',
      gardenCardBorder: '#1a1a1a',
      gardenCardBorderHover: '#9b2226',
      gardenCardThumbnail: '#f1eee7',
      gardenCardAspect: '3 / 4',
      gardenCardMinWidth: '200px',
      fileTreeItemSelected: '#f3e4e2',
      fileTreeItemTextSelected: '#9b2226',
      fileTreeItemHover: '#f1eee7',
      editorBackground: '#fdfcf9',
      markdownHeading: '#1a1a1a',
      markdownLink: '#9b2226',
      // Panes: ink rules only — every pane black-on-paper, headers in small caps
      paneCollaboration: '#1a1a1a',
      paneArtifacts: '#1a1a1a',
      paneWorkshop: '#1a1a1a',
      paneDetails: '#1a1a1a',
      paneHistory: '#1a1a1a',
      paneExport: '#1a1a1a',
      paneSync: '#1a1a1a',
      panePublish: '#9b2226',
      paneStore: '#1a1a1a',
    },
  },
  // ════════════════════════════════════════════════════
  // DARK — tonal variations on café (warm, readable)
  // ════════════════════════════════════════════════════

  // Blade Runner — rain-black indigo, neon orange and cyan, magenta signage.
  // Every pane keeps the same wet-asphalt body; its identity is a neon frame.
  {
    id: 'blade-runner',
    name: 'Blade Runner',
    section: 'Dark',
    overrides: {
      bg: '#04050d',
      panel: '#0a0d1a',
      surface: '#10142a',
      surfaceSolid: '#10142a',
      accent: '#ff6a1a',
      accentMuted: '#2a1408',
      border: '#1a2a4a',
      text: '#e8ecf6',
      textMuted: '#7d88ad',
      heading: '#ffb86b',
      caption: '#16d5e8',
      highlight: '#16d5e8',
      error: '#ff3b5c',
      warning: '#ffb020',
      success: '#2ee6a6',
      radius: '0.25rem',
      radiusSm: '0.125rem',
      radiusLg: '0.5rem',
      paneGap: '10px',
      workspacePadding: '10px',
      paneBorderWidth: '2px',
      paneHeaderHeight: '30px',
      paneHeaderRadius: '0px',
      fontDisplay: "'JetBrains Mono', monospace",
      // Top bar: a dark visor with an orange readout
      toolbar: '#06070f',
      toolbarText: '#ffb86b',
      toolbarTextMuted: '#7d88ad',
      toolbarBorder: '#1a2a4a',
      toolbarDivider: '#1a2a4a',
      iconButtonIcon: '#16d5e8',
      iconButtonIconHover: '#ff6a1a',
      iconButtonHover: '#10142a',
      // Chat: the user speaks in orange, the machine in cold cyan-grey
      chat: '#0a0d1a',
      chatText: '#e8ecf6',
      chatTextMuted: '#7d88ad',
      chatUserBubble: '#2a1408',
      chatUserBubbleText: '#ffb86b',
      chatUserBubbleBorder: '#ff6a1a',
      chatAiBubble: '#10142a',
      chatAiText: '#d6e4f0',
      chatAiBubbleBorder: '#1a2a4a',
      chatInput: '#06070f',
      chatInputText: '#e8ecf6',
      chatInputBorder: '#1a2a4a',
      chatInputBorderFocus: '#16d5e8',
      chatInputPlaceholder: '#4d5878',
      chatSendButton: '#ff6a1a',
      chatSendButtonHover: '#ff8a45',
      chatSendButtonIcon: '#04050d',
      // Controls
      primaryButton: '#ff6a1a',
      primaryButtonText: '#04050d',
      primaryButtonBorder: '#ff6a1a',
      actionButton: '#10142a',
      actionButtonText: '#16d5e8',
      actionButtonBorder: '#1a2a4a',
      badge: '#0e2a30',
      badgeText: '#16d5e8',
      badgeBorder: '#16d5e8',
      // Cards
      gardenCard: '#0a0d1a',
      gardenCardHover: '#10142a',
      gardenCardBorder: '#1a2a4a',
      gardenCardBorderHover: '#16d5e8',
      gardenCardTitle: '#ffb86b',
      gardenCardText: '#a7b1cf',
      gardenCardMeta: '#5d6890',
      gardenCardThumbnail: '#04050d',
      growthCard: '#0a0d1a',
      growthCardHover: '#10142a',
      growthCardActive: '#14213d',
      growthCardText: '#e8ecf6',
      growthCardTextMuted: '#7d88ad',
      growthCardLabel: '#16d5e8',
      growthDot: '#4d5878',
      growthDotActive: '#ff6a1a',
      overlayBadge: 'rgba(4, 5, 13, 0.75)',
      overlayBadgeText: '#16d5e8',
      // File tree
      fileTree: '#0a0d1a',
      fileTreeItemText: '#d6e4f0',
      fileTreeItemIcon: '#7d88ad',
      fileTreeItemHover: '#10142a',
      fileTreeItemSelected: '#14213d',
      fileTreeItemTextSelected: '#ffb86b',
      // Code
      syntaxComment: '#4d5878',
      syntaxKeyword: '#ff6a1a',
      syntaxString: '#16d5e8',
      syntaxNumber: '#ffb020',
      syntaxType: '#ff2bd6',
      syntaxFunction: '#ffb86b',
      syntaxPunctuation: '#7d88ad',
      syntaxVariable: '#d6e4f0',
      syntaxTag: '#ff2bd6',
      syntaxAttribute: '#16d5e8',
      // Ambient: sodium lamps over wet streets
      bloomBg1: '#04050d',
      bloomBg2: '#000000',
      bloom1: '#ff6a1a',
      bloom2: '#16d5e8',
      bloom3: '#ff2bd6',
      bloom4: '#1a2a4a',
      bloom5: '#ffb020',
      bloom6: '#0b3a44',
      bloomBlur: '80px',
      bloomOpacity: '0.55',
      // Pane identities — neon frames on the same wet-asphalt body
      paneCollaboration: '#ff2bd6',
      paneArtifacts: '#ffb020',
      paneWorkshop: '#16d5e8',
      paneDetails: '#2ee6a6',
      paneHistory: '#ff6a1a',
      paneExport: '#8a7cff',
      paneSync: '#5cc8ff',
      panePublish: '#ff3b5c',
      paneStore: '#ffd36b',
      ...neonFrames({
        paneCollaboration: ['#ff2bd6', '#7a1a9a'],
        paneArtifacts: ['#ffb020', '#8a4a00'],
        paneWorkshop: ['#16d5e8', '#0b3a44'],
        paneDetails: ['#2ee6a6', '#0b4a3a'],
        paneHistory: ['#ff6a1a', '#7a2a00'],
        paneExport: ['#8a7cff', '#2a1a7a'],
        paneSync: ['#5cc8ff', '#0b2a4a'],
        panePublish: ['#ff3b5c', '#6a0a1a'],
        paneStore: ['#ffd36b', '#7a5a00'],
      }),
    },
  },

  // ── Explorations (dark) ─────────────────────────────────────────────────

  // Terminal — green phosphor on black. Everything is text; nothing is round.
  {
    id: 'terminal',
    name: 'Terminal',
    section: 'Dark',
    overrides: {
      bg: '#000000',
      panel: '#000000',
      surface: '#061006',
      surfaceSolid: '#061006',
      accent: '#33ff66',
      accentMuted: '#0a2a12',
      border: '#1f6f2f',
      text: '#33ff66',
      textMuted: '#1f9f3f',
      heading: '#66ff99',
      caption: '#1f9f3f',
      highlight: '#33ff66',
      error: '#ff5555',
      warning: '#ffcc33',
      success: '#33ff66',
      radius: '0px',
      radiusSm: '0px',
      radiusLg: '0px',
      paneGap: '0px',
      workspacePadding: '0px',
      paneBorderWidth: '1px',
      paneHeaderHeight: '22px',
      paneHeaderRadius: '0px',
      paneHeaderPadding: '0px',
      paneHeaderLabelCase: 'lowercase',
      paneHeaderLabelTracking: '0',
      paneHeaderIconDisplay: 'none',
      fontDisplay: "Menlo, 'JetBrains Mono', monospace",
      fontBody: "Menlo, 'JetBrains Mono', monospace",
      fontMono: "Menlo, 'JetBrains Mono', monospace",
      letterSpacingBody: '0',
      lineHeightBody: '1.4',
      density: '0.9',
      motionScale: '0',
      elevationPanel: 'none',
      elevationCardHover: 'none',
      elevationModal: 'none',
      scrim: 'rgb(0 0 0 / 0.7)',
      toolbar: '#000000',
      toolbarText: '#33ff66',
      toolbarTextMuted: '#1f9f3f',
      toolbarBorder: '#1f6f2f',
      toolbarDivider: '#1f6f2f',
      iconButtonIcon: '#1f9f3f',
      iconButtonIconHover: '#33ff66',
      iconButtonHover: '#061006',
      chat: '#000000',
      chatText: '#33ff66',
      chatTextMuted: '#1f9f3f',
      chatUserBubble: '#000000',
      chatUserBubbleText: '#66ff99',
      chatUserBubbleBorder: '#1f6f2f',
      chatAiBubble: '#000000',
      chatAiText: '#33ff66',
      chatAiBubbleBorder: '#1f6f2f',
      chatInput: '#000000',
      chatInputText: '#33ff66',
      chatInputBorder: '#1f6f2f',
      chatInputBorderFocus: '#33ff66',
      chatInputPlaceholder: '#1f6f2f',
      chatSendButton: '#1f6f2f',
      chatSendButtonHover: '#33ff66',
      chatSendButtonIcon: '#000000',
      primaryButton: '#1f6f2f',
      primaryButtonText: '#000000',
      primaryButtonBorder: '#33ff66',
      actionButton: '#000000',
      actionButtonText: '#33ff66',
      actionButtonBorder: '#1f6f2f',
      gardenCard: '#000000',
      gardenCardHover: '#061006',
      gardenCardBorder: '#1f6f2f',
      gardenCardBorderHover: '#33ff66',
      gardenCardTitle: '#66ff99',
      gardenCardText: '#33ff66',
      gardenCardMeta: '#1f9f3f',
      gardenCardThumbnail: '#000000',
      gardenCardAspect: '4 / 3',
      growthCard: '#000000',
      growthCardHover: '#061006',
      growthCardActive: '#0a2a12',
      growthCardText: '#33ff66',
      growthCardTextMuted: '#1f9f3f',
      growthCardLabel: '#66ff99',
      overlayBadge: '#1f6f2f',
      overlayBadgeText: '#000000',
      fileTree: '#000000',
      fileTreeItemText: '#33ff66',
      fileTreeItemIcon: '#1f9f3f',
      fileTreeItemHover: '#061006',
      fileTreeItemSelected: '#1f6f2f',
      fileTreeItemTextSelected: '#000000',
      editorBackground: '#000000',
      editorCursor: '#33ff66',
      editorSelection: 'rgba(51, 255, 102, 0.25)',
      syntaxComment: '#1f9f3f',
      syntaxKeyword: '#66ff99',
      syntaxString: '#33ff66',
      syntaxNumber: '#99ffbb',
      syntaxType: '#66ff99',
      syntaxFunction: '#ccffdd',
      syntaxPunctuation: '#1f9f3f',
      syntaxVariable: '#33ff66',
      syntaxTag: '#66ff99',
      syntaxAttribute: '#99ffbb',
      ...NO_BLOOM,
      ...uniformPanes({
        body: '#000000',
        surface: '#061006',
        border: '#1f6f2f',
        header: '#000000',
        headerText: '#33ff66',
        headerBorder: '#1f6f2f',
        text: '#33ff66',
        textMuted: '#1f9f3f',
        caption: '#1f9f3f',
        heading: '#66ff99',
        accent: '#33ff66',
        radius: '0px',
        headerRadius: '0px',
      }),
    },
  },

  // Amber CRT — a warmer terminal; vintage, curved corners like a tube.
  {
    id: 'amber-crt',
    name: 'Amber CRT',
    section: 'Dark',
    overrides: {
      bg: '#0b0803',
      panel: '#120c04',
      surface: '#1a1206',
      surfaceSolid: '#1a1206',
      accent: '#ffb000',
      accentMuted: '#3a2600',
      border: '#6b4a00',
      text: '#ffb000',
      textMuted: '#b07a00',
      heading: '#ffd166',
      caption: '#b07a00',
      error: '#ff5e3a',
      warning: '#ffd166',
      success: '#ffb000',
      radius: '18px',
      radiusSm: '6px',
      paneGap: '14px',
      workspacePadding: '14px',
      paneBorderWidth: '2px',
      paneHeaderHeight: '26px',
      paneHeaderLabelCase: 'uppercase',
      paneHeaderLabelTracking: '0.15em',
      fontDisplay: "'JetBrains Mono', monospace",
      fontBody: "'JetBrains Mono', monospace",
      lineHeightBody: '1.45',
      motionScale: '0.5',
      elevationPanel: '0 0 40px rgb(255 176 0 / 0.08) inset',
      elevationModal: '0 0 80px rgb(255 176 0 / 0.15)',
      scrim: 'rgb(11 8 3 / 0.85)',
      toolbar: '#0b0803',
      toolbarText: '#ffb000',
      toolbarTextMuted: '#b07a00',
      toolbarBorder: '#6b4a00',
      toolbarDivider: '#6b4a00',
      iconButtonIcon: '#b07a00',
      iconButtonIconHover: '#ffd166',
      chat: '#120c04',
      chatText: '#ffb000',
      chatTextMuted: '#b07a00',
      chatUserBubble: '#3a2600',
      chatUserBubbleText: '#ffd166',
      chatUserBubbleBorder: '#6b4a00',
      chatAiBubble: '#1a1206',
      chatAiText: '#ffb000',
      chatAiBubbleBorder: '#6b4a00',
      chatInput: '#0b0803',
      chatInputText: '#ffb000',
      chatInputBorder: '#6b4a00',
      chatInputBorderFocus: '#ffb000',
      chatInputPlaceholder: '#6b4a00',
      chatSendButton: '#ffb000',
      chatSendButtonHover: '#ffd166',
      chatSendButtonIcon: '#0b0803',
      primaryButton: '#ffb000',
      primaryButtonText: '#0b0803',
      primaryButtonBorder: '#ffb000',
      gardenCard: '#120c04',
      gardenCardHover: '#1a1206',
      gardenCardBorder: '#6b4a00',
      gardenCardBorderHover: '#ffb000',
      gardenCardTitle: '#ffd166',
      gardenCardText: '#d99a00',
      gardenCardMeta: '#b07a00',
      gardenCardThumbnail: '#0b0803',
      growthCard: '#120c04',
      growthCardText: '#ffb000',
      growthCardTextMuted: '#b07a00',
      growthCardLabel: '#ffd166',
      overlayBadge: '#3a2600',
      overlayBadgeText: '#ffd166',
      fileTree: '#120c04',
      fileTreeItemText: '#ffb000',
      fileTreeItemIcon: '#b07a00',
      fileTreeItemSelected: '#3a2600',
      fileTreeItemTextSelected: '#ffd166',
      editorBackground: '#0b0803',
      editorCursor: '#ffb000',
      editorSelection: 'rgba(255, 176, 0, 0.25)',
      syntaxComment: '#8a6200',
      syntaxKeyword: '#ffd166',
      syntaxString: '#ffb000',
      syntaxNumber: '#ffe0a3',
      syntaxType: '#ffd166',
      syntaxFunction: '#fff1cc',
      syntaxPunctuation: '#b07a00',
      syntaxVariable: '#ffb000',
      syntaxTag: '#ffd166',
      syntaxAttribute: '#ffe0a3',
      bloomBg1: '#0b0803',
      bloomBg2: '#000000',
      bloom1: '#3a2600',
      bloom2: '#1a1206',
      bloom3: '#3a2600',
      bloom4: '#000000',
      bloom5: '#2a1a00',
      bloom6: '#000000',
      bloomBlur: '120px',
      ...uniformPanes({
        body: '#120c04',
        surface: '#1a1206',
        border: 'radial-gradient(circle at 50% 50%, #ffb000, #6b4a00 70%)',
        header: '#0b0803',
        headerText: '#ffb000',
        text: '#ffb000',
        textMuted: '#b07a00',
        caption: '#b07a00',
        heading: '#ffd166',
        accent: '#ffb000',
        radius: '18px',
        headerRadius: '12px',
      }),
    },
  },

  // Midnight Pro — subdued professional, dark. One blue, hairlines, quiet.
  {
    id: 'midnight-pro',
    name: 'Midnight Pro',
    section: 'Dark',
    overrides: {
      bg: '#0f1217',
      panel: '#151a21',
      surface: '#1b2129',
      surfaceSolid: '#1b2129',
      accent: '#6ea8ff',
      accentMuted: '#1a2a44',
      border: '#252c36',
      text: '#e6e9ee',
      textMuted: '#8b96a5',
      heading: '#ffffff',
      caption: '#8b96a5',
      error: '#ff6b6b',
      warning: '#f5c451',
      success: '#4fd18b',
      radius: '6px',
      radiusSm: '4px',
      paneGap: '8px',
      workspacePadding: '8px',
      paneBorderWidth: '1px',
      paneHeaderHeight: '32px',
      paneHeaderLabelCase: 'none',
      paneHeaderLabelTracking: '0',
      paneHeaderLabelFont: 'var(--font-body)',
      paneHeaderLabelSize: '12px',
      paneHeaderLabelWeight: '500',
      fontDisplay: "-apple-system, 'Segoe UI', Inter, system-ui, sans-serif",
      fontBody: "-apple-system, 'Segoe UI', Inter, system-ui, sans-serif",
      elevationPanel: '0 1px 2px rgb(0 0 0 / 0.4)',
      elevationCardHover: '0 6px 20px rgb(0 0 0 / 0.35)',
      toolbar: '#0f1217',
      toolbarText: '#e6e9ee',
      toolbarTextMuted: '#8b96a5',
      toolbarBorder: '#252c36',
      toolbarDivider: '#252c36',
      iconButtonIcon: '#8b96a5',
      iconButtonIconHover: '#6ea8ff',
      chat: '#151a21',
      chatUserBubble: '#1a2a44',
      chatUserBubbleText: '#dbe7ff',
      chatUserBubbleBorder: '#1a2a44',
      chatAiBubble: '#1b2129',
      chatAiText: '#e6e9ee',
      chatAiBubbleBorder: '#252c36',
      chatInput: '#0f1217',
      chatInputBorder: '#252c36',
      chatInputBorderFocus: '#6ea8ff',
      chatSendButton: '#6ea8ff',
      chatSendButtonIcon: '#0f1217',
      primaryButton: '#6ea8ff',
      primaryButtonText: '#0f1217',
      gardenCard: '#151a21',
      gardenCardHover: '#1b2129',
      gardenCardBorder: '#252c36',
      gardenCardBorderHover: '#6ea8ff',
      gardenCardTitle: '#ffffff',
      gardenCardText: '#a6b0bd',
      gardenCardMeta: '#6b7683',
      gardenCardThumbnail: '#0f1217',
      growthCardLabel: '#6ea8ff',
      growthDotActive: '#6ea8ff',
      fileTreeItemSelected: '#1a2a44',
      fileTreeItemTextSelected: '#dbe7ff',
      editorBackground: '#0f1217',
      syntaxKeyword: '#6ea8ff',
      syntaxString: '#4fd18b',
      syntaxNumber: '#f5c451',
      syntaxType: '#c3a6ff',
      syntaxFunction: '#e6e9ee',
      syntaxTag: '#6ea8ff',
      syntaxAttribute: '#f5c451',
      ...NO_BLOOM,
      ...uniformPanes({
        body: '#151a21',
        surface: '#1b2129',
        border: '#252c36',
        header: '#151a21',
        headerText: '#e6e9ee',
        headerBorder: '#252c36',
        caption: '#8b96a5',
        heading: '#ffffff',
        accent: '#6ea8ff',
        radius: '6px',
        headerRadius: '0px',
        headerHeight: '32px',
      }),
    },
  },

  // Deep Sea — cool and dark: glass panes over a slow teal bloom.
  {
    id: 'deep-sea',
    name: 'Deep Sea',
    section: 'Dark',
    overrides: {
      bg: '#03080d',
      panel: 'rgba(8, 22, 34, 0.72)',
      surface: 'rgba(14, 38, 56, 0.7)',
      surfaceSolid: '#0e2638',
      accent: '#3ee0c5',
      accentMuted: '#0b3a36',
      border: 'rgba(62, 224, 197, 0.22)',
      text: '#d9f3f0',
      textMuted: '#7fb3ad',
      heading: '#ffffff',
      caption: '#3ee0c5',
      error: '#ff6b81',
      warning: '#ffcf6b',
      success: '#3ee0c5',
      radius: '14px',
      radiusSm: '8px',
      paneGap: '12px',
      workspacePadding: '12px',
      paneBorderWidth: '1px',
      paneHeaderHeight: '30px',
      paneHeaderLabelCase: 'none',
      paneHeaderLabelFont: 'var(--font-body)',
      paneHeaderLabelSize: '12px',
      paneHeaderLabelTracking: '0.02em',
      elevationPanel: '0 20px 50px rgb(0 0 0 / 0.45)',
      elevationCardHover: '0 20px 50px rgb(0 0 0 / 0.45)',
      motionScale: '1.6',
      toolbar: 'rgba(3, 8, 13, 0.7)',
      toolbarText: '#d9f3f0',
      toolbarTextMuted: '#7fb3ad',
      toolbarBorder: 'rgba(62, 224, 197, 0.18)',
      toolbarDivider: 'rgba(62, 224, 197, 0.18)',
      iconButtonIcon: '#7fb3ad',
      iconButtonIconHover: '#3ee0c5',
      chat: 'transparent',
      chatUserBubble: 'rgba(62, 224, 197, 0.16)',
      chatUserBubbleText: '#e6fffb',
      chatUserBubbleBorder: 'rgba(62, 224, 197, 0.3)',
      chatAiBubble: 'rgba(14, 38, 56, 0.7)',
      chatAiText: '#d9f3f0',
      chatAiBubbleBorder: 'rgba(62, 224, 197, 0.15)',
      chatInput: 'rgba(3, 8, 13, 0.6)',
      chatInputBorder: 'rgba(62, 224, 197, 0.25)',
      chatInputBorderFocus: '#3ee0c5',
      chatSendButton: '#3ee0c5',
      chatSendButtonIcon: '#03080d',
      primaryButton: '#3ee0c5',
      primaryButtonText: '#03080d',
      gardenCard: 'rgba(8, 22, 34, 0.72)',
      gardenCardHover: 'rgba(14, 38, 56, 0.8)',
      gardenCardBorder: 'rgba(62, 224, 197, 0.22)',
      gardenCardBorderHover: '#3ee0c5',
      gardenCardTitle: '#ffffff',
      gardenCardText: '#a9d6d1',
      gardenCardMeta: '#7fb3ad',
      gardenCardThumbnail: '#03080d',
      growthCard: 'rgba(8, 22, 34, 0.72)',
      growthCardLabel: '#3ee0c5',
      growthDotActive: '#3ee0c5',
      editorBackground: '#03080d',
      syntaxKeyword: '#3ee0c5',
      syntaxString: '#9ef0ff',
      syntaxNumber: '#ffcf6b',
      syntaxType: '#7fb3ad',
      syntaxFunction: '#ffffff',
      bloomBg1: '#03080d',
      bloomBg2: '#000000',
      bloom1: '#0b3a36',
      bloom2: '#0e2638',
      bloom3: '#164e63',
      bloom4: '#03080d',
      bloom5: '#0b3a36',
      bloom6: '#062c3a',
      bloomBlur: '100px',
      bloomSpeed: '0.4',
      ...uniformPanes({
        body: 'rgba(8, 22, 34, 0.72)',
        surface: 'rgba(14, 38, 56, 0.7)',
        border: 'rgba(62, 224, 197, 0.22)',
        header: 'transparent',
        headerText: '#d9f3f0',
        caption: '#3ee0c5',
        heading: '#ffffff',
        accent: '#3ee0c5',
        radius: '14px',
        headerRadius: '10px',
      }),
    },
  },

  // Darkroom — vintage: sepia negatives, cream captions, a red safelight accent.
  {
    id: 'darkroom',
    name: 'Darkroom',
    section: 'Dark',
    overrides: {
      bg: '#1b1410',
      panel: '#231a14',
      surface: '#2c211a',
      surfaceSolid: '#2c211a',
      accent: '#d9583b',
      accentMuted: '#3d221a',
      border: '#4a382c',
      text: '#efe3d0',
      textMuted: '#a8927a',
      heading: '#f7ecd8',
      caption: '#c7a67e',
      error: '#e0553a',
      warning: '#d9a441',
      success: '#8fae6a',
      radius: '4px',
      radiusSm: '2px',
      paneGap: '10px',
      workspacePadding: '10px',
      paneBorderWidth: '1px',
      paneHeaderHeight: '30px',
      paneHeaderLabelFont: 'var(--font-display)',
      paneHeaderLabelCase: 'none',
      paneHeaderLabelSize: '14px',
      paneHeaderLabelWeight: '500',
      paneHeaderLabelTracking: '0.02em',
      fontDisplay: "'Cormorant Garamond', Georgia, serif",
      fontBody: "Georgia, 'Times New Roman', serif",
      letterSpacingDisplay: '0.01em',
      lineHeightBody: '1.55',
      elevationPanel: '0 2px 0 #4a382c',
      toolbar: '#1b1410',
      toolbarText: '#efe3d0',
      toolbarTextMuted: '#a8927a',
      toolbarBorder: '#4a382c',
      toolbarDivider: '#4a382c',
      iconButtonIcon: '#a8927a',
      iconButtonIconHover: '#d9583b',
      chat: '#231a14',
      chatUserBubble: '#3d221a',
      chatUserBubbleText: '#f7ecd8',
      chatUserBubbleBorder: '#4a382c',
      chatAiBubble: '#2c211a',
      chatAiText: '#efe3d0',
      chatAiBubbleBorder: '#4a382c',
      chatInput: '#1b1410',
      chatInputBorder: '#4a382c',
      chatInputBorderFocus: '#d9583b',
      chatSendButton: '#d9583b',
      chatSendButtonIcon: '#1b1410',
      primaryButton: '#d9583b',
      primaryButtonText: '#1b1410',
      gardenCard: '#231a14',
      gardenCardHover: '#2c211a',
      gardenCardBorder: '#4a382c',
      gardenCardBorderHover: '#c7a67e',
      gardenCardTitle: '#f7ecd8',
      gardenCardText: '#c7b39a',
      gardenCardMeta: '#a8927a',
      gardenCardThumbnail: '#120d0a',
      gardenCardAspect: '3 / 2',
      growthCardLabel: '#c7a67e',
      growthDotActive: '#d9583b',
      overlayBadge: 'rgba(27, 20, 16, 0.8)',
      overlayBadgeText: '#efe3d0',
      editorBackground: '#1b1410',
      syntaxKeyword: '#d9583b',
      syntaxString: '#c7a67e',
      syntaxNumber: '#d9a441',
      syntaxType: '#8fae6a',
      syntaxFunction: '#f7ecd8',
      syntaxTag: '#d9583b',
      syntaxAttribute: '#c7a67e',
      bloomBg1: '#1b1410',
      bloomBg2: '#0f0a08',
      bloom1: '#3d221a',
      bloom2: '#2c211a',
      bloom3: '#4a2a1a',
      bloom4: '#1b1410',
      bloom5: '#3a2c20',
      bloom6: '#1b1410',
      bloomBlur: '90px',
      ...uniformPanes({
        body: '#231a14',
        surface: '#2c211a',
        border: 'repeating-linear-gradient(45deg, #4a382c 0 3px, #2c211a 3px 6px)',
        header: '#1b1410',
        headerText: '#efe3d0',
        caption: '#c7a67e',
        heading: '#f7ecd8',
        accent: '#d9583b',
        radius: '4px',
        headerRadius: '2px',
        borderWidth: '2px',
      }),
    },
  },

  // Brutalist — black, white, one red. Thick rules, zero radius, big type.
  {
    id: 'brutalist',
    name: 'Brutalist',
    section: 'Dark',
    overrides: {
      bg: '#000000',
      panel: '#000000',
      surface: '#111111',
      surfaceSolid: '#111111',
      accent: '#ff2a00',
      accentMuted: '#330800',
      border: '#ffffff',
      text: '#ffffff',
      textMuted: '#9a9a9a',
      heading: '#ffffff',
      caption: '#ffffff',
      error: '#ff2a00',
      warning: '#ffffff',
      success: '#ffffff',
      radius: '0px',
      radiusSm: '0px',
      radiusLg: '0px',
      paneGap: '16px',
      workspacePadding: '16px',
      paneBorderWidth: '3px',
      paneHeaderHeight: '40px',
      paneHeaderRadius: '0px',
      paneHeaderLabelFont: 'var(--font-display)',
      paneHeaderLabelSize: '18px',
      paneHeaderLabelWeight: '800',
      paneHeaderLabelCase: 'uppercase',
      paneHeaderLabelTracking: '-0.02em',
      paneHeaderIconDisplay: 'none',
      fontDisplay: "'Helvetica Neue', Helvetica, Arial, sans-serif",
      fontBody: "'Helvetica Neue', Helvetica, Arial, sans-serif",
      fontScale: '1.05',
      letterSpacingDisplay: '-0.02em',
      motionScale: '0',
      elevationPanel: 'none',
      elevationCardHover: '8px 8px 0 #ffffff',
      elevationModal: '12px 12px 0 #ff2a00',
      scrim: 'rgb(0 0 0 / 0.8)',
      toolbar: '#ffffff',
      toolbarText: '#000000',
      toolbarTextMuted: '#444444',
      toolbarBorder: '#000000',
      toolbarDivider: '#000000',
      iconButtonIcon: '#000000',
      iconButtonIconHover: '#ff2a00',
      chat: '#000000',
      chatUserBubble: '#ffffff',
      chatUserBubbleText: '#000000',
      chatUserBubbleBorder: '#ffffff',
      chatAiBubble: '#000000',
      chatAiText: '#ffffff',
      chatAiBubbleBorder: '#ffffff',
      chatInput: '#000000',
      chatInputBorder: '#ffffff',
      chatInputBorderFocus: '#ff2a00',
      chatSendButton: '#ff2a00',
      chatSendButtonIcon: '#000000',
      primaryButton: '#ffffff',
      primaryButtonText: '#000000',
      primaryButtonBorder: '#ffffff',
      actionButton: '#000000',
      actionButtonText: '#ffffff',
      actionButtonBorder: '#ffffff',
      gardenCard: '#000000',
      gardenCardHover: '#111111',
      gardenCardBorder: '#ffffff',
      gardenCardBorderHover: '#ff2a00',
      gardenCardTitle: '#ffffff',
      gardenCardText: '#cccccc',
      gardenCardMeta: '#9a9a9a',
      gardenCardThumbnail: '#111111',
      gardenCardAspect: '1 / 1',
      gardenGridGap: '24px',
      growthCard: '#000000',
      growthCardLabel: '#ff2a00',
      growthDotActive: '#ff2a00',
      overlayBadge: '#ffffff',
      overlayBadgeText: '#000000',
      fileTree: '#000000',
      fileTreeItemSelected: '#ffffff',
      fileTreeItemTextSelected: '#000000',
      editorBackground: '#000000',
      syntaxKeyword: '#ff2a00',
      syntaxString: '#ffffff',
      syntaxNumber: '#ffffff',
      syntaxType: '#ffffff',
      syntaxFunction: '#ffffff',
      syntaxComment: '#666666',
      ...NO_BLOOM,
      ...uniformPanes({
        body: '#000000',
        surface: '#111111',
        border: '#ffffff',
        header: '#ffffff',
        headerText: '#000000',
        caption: '#ffffff',
        heading: '#ffffff',
        accent: '#ff2a00',
        radius: '0px',
        headerRadius: '0px',
      }),
    },
  },

  // Obsidian — soft black, neutral, high readability
  {
    id: 'obsidian',
    name: 'Obsidian',
    section: 'Dark',
    overrides: {
      bg: '#121314',
      surface: '#191A1B',
      panel: '#191A1B',
      accent: '#c9c9c9',
      border: '#353638',
      text: '#d5d8d9',
      textMuted: '#9b9b9b',
      paneCollaboration: '#b88f82',
      paneArtifacts: '#cdb27d',
      paneWorkshop: '#aab882',
      paneDetails: '#7fc29a',
      paneHistory: '#7fa7c2',
      paneExport: '#7f8dc2',
      paneSync: '#8f82b8',
      panePublish: '#bf8a97',
      paneStore: '#b5a78d',
      ...ghostPanes(
        {
          paneCollaboration: '#a08880',
          paneArtifacts: '#b0a080',
          paneWorkshop: '#98a080',
          paneDetails: '#80a890',
          paneHistory: '#8098a8',
          paneExport: '#8088a8',
          paneSync: '#8880a0',
          panePublish: '#a88890',
          paneStore: '#a09888',
        },
        '#1e1f20',
        '#8C8C8C',
      ),
    },
  },

  // Slate — cool blue tint on obsidian base
  {
    id: 'slate',
    name: 'Slate',
    section: 'Dark',
    overrides: {
      bg: '#121316',
      surface: '#191A1E',
      panel: '#191A1E',
      surfaceSolid: '#191A1E',
      toolbar: '#191A1E',
      accent: '#79a0d3',
      border: '#34353d',
      text: '#d4d9e3',
      textMuted: '#7a88bc',
      paneCollaboration: '#b88f82',
      paneArtifacts: '#cdb27d',
      paneWorkshop: '#aab882',
      paneDetails: '#7fc29a',
      paneHistory: '#7fa7c2',
      paneExport: '#7f8dc2',
      paneSync: '#8f82b8',
      panePublish: '#bf8a97',
      paneStore: '#b5a78d',
      ...ghostPanes(
        {
          paneCollaboration: '#a08880',
          paneArtifacts: '#b0a080',
          paneWorkshop: '#98a080',
          paneDetails: '#80a890',
          paneHistory: '#8098a8',
          paneExport: '#8088a8',
          paneSync: '#8880a0',
          panePublish: '#a88890',
          paneStore: '#a09888',
        },
        '#1e1f22',
        '#7880A0',
      ),
    },
  },

  // Moss — green tint on obsidian base
  {
    id: 'moss',
    name: 'Moss',
    section: 'Dark',
    overrides: {
      bg: '#121413',
      surface: '#191B1A',
      panel: '#191B1A',
      surfaceSolid: '#191B1A',
      toolbar: '#191B1A',
      accent: '#88bc88',
      border: '#353835',
      text: '#d5dad5',
      textMuted: '#86a186',
      paneCollaboration: '#b88f82',
      paneArtifacts: '#cdb27d',
      paneWorkshop: '#aab882',
      paneDetails: '#7fc29a',
      paneHistory: '#7fa7c2',
      paneExport: '#7f8dc2',
      paneSync: '#8f82b8',
      panePublish: '#bf8a97',
      paneStore: '#b5a78d',
      ...ghostPanes(
        {
          paneCollaboration: '#a08880',
          paneArtifacts: '#b0a080',
          paneWorkshop: '#98a080',
          paneDetails: '#80a890',
          paneHistory: '#8098a8',
          paneExport: '#8088a8',
          paneSync: '#8880a0',
          panePublish: '#a88890',
          paneStore: '#a09888',
        },
        '#1e201f',
        '#7C8C7C',
      ),
    },
  },

  // Ember — red tint on obsidian base
  {
    id: 'ember',
    name: 'Ember',
    section: 'Dark',
    overrides: {
      bg: '#141213',
      surface: '#1B1919',
      panel: '#1B1919',
      surfaceSolid: '#1B1919',
      toolbar: '#1B1919',
      accent: '#d38679',
      border: '#383535',
      text: '#dad5d5',
      textMuted: '#a18686',
      paneCollaboration: '#b88f82',
      paneArtifacts: '#cdb27d',
      paneWorkshop: '#aab882',
      paneDetails: '#7fc29a',
      paneHistory: '#7fa7c2',
      paneExport: '#7f8dc2',
      paneSync: '#8f82b8',
      panePublish: '#bf8a97',
      paneStore: '#b5a78d',
      ...ghostPanes(
        {
          paneCollaboration: '#a08880',
          paneArtifacts: '#b0a080',
          paneWorkshop: '#98a080',
          paneDetails: '#80a890',
          paneHistory: '#8098a8',
          paneExport: '#8088a8',
          paneSync: '#8880a0',
          panePublish: '#a88890',
          paneStore: '#a09888',
        },
        '#201e1e',
        '#8C7C7C',
      ),
    },
  },

  // Café — warm brown tint on obsidian base
  {
    id: 'cafe',
    name: 'Café',
    section: 'Dark',
    overrides: {
      bg: '#141312',
      surface: '#1B1A18',
      panel: '#1B1A18',
      surfaceSolid: '#1B1A18',
      toolbar: '#1B1A18',
      accent: '#dcae69',
      border: '#393732',
      text: '#dbd8d0',
      textMuted: '#a79a7f',
      paneCollaboration: '#b88f82',
      paneArtifacts: '#cdb27d',
      paneWorkshop: '#aab882',
      paneDetails: '#7fc29a',
      paneHistory: '#7fa7c2',
      paneExport: '#7f8dc2',
      paneSync: '#8f82b8',
      panePublish: '#bf8a97',
      paneStore: '#b5a78d',
      ...ghostPanes(
        {
          paneCollaboration: '#a08880',
          paneArtifacts: '#b0a080',
          paneWorkshop: '#98a080',
          paneDetails: '#80a890',
          paneHistory: '#8098a8',
          paneExport: '#8088a8',
          paneSync: '#8880a0',
          panePublish: '#a88890',
          paneStore: '#a09888',
        },
        '#201f1e',
        '#908878',
      ),
    },
  },

  // ════════════════════════════════════════════════════
  // LIGHT — tonal variations on parchment/ivory (warm, readable)
  // ════════════════════════════════════════════════════

  // ── Explorations (light) ────────────────────────────────────────────────

  // Feed — the photo-app look: white, round, one warm gradient on headers.
  {
    id: 'feed',
    name: 'Feed',
    section: 'Light',
    overrides: {
      bg: '#fafafa',
      panel: '#ffffff',
      surface: '#f2f2f2',
      surfaceSolid: '#ffffff',
      accent: '#d62976',
      accentMuted: '#fde3ee',
      border: '#e6e6e6',
      text: '#262626',
      textMuted: '#8e8e8e',
      heading: '#000000',
      caption: '#8e8e8e',
      error: '#ed4956',
      warning: '#f59e0b',
      success: '#2db27d',
      radius: '20px',
      radiusSm: '12px',
      radiusLg: '28px',
      paneGap: '14px',
      workspacePadding: '14px',
      paneBorderWidth: '2px',
      paneHeaderHeight: '36px',
      paneHeaderRadius: '999px',
      paneHeaderLabelFont: 'var(--font-body)',
      paneHeaderLabelCase: 'none',
      paneHeaderLabelSize: '13px',
      paneHeaderLabelWeight: '600',
      paneHeaderLabelTracking: '0',
      fontDisplay: "-apple-system, 'Segoe UI', Helvetica, Arial, sans-serif",
      fontBody: "-apple-system, 'Segoe UI', Helvetica, Arial, sans-serif",
      elevationPanel: '0 1px 3px rgb(0 0 0 / 0.06)',
      elevationCard: '0 1px 3px rgb(0 0 0 / 0.06)',
      elevationCardHover: '0 12px 30px rgb(0 0 0 / 0.12)',
      scrim: 'rgb(0 0 0 / 0.5)',
      toolbar: '#ffffff',
      toolbarText: '#262626',
      toolbarTextMuted: '#8e8e8e',
      toolbarBorder: '#e6e6e6',
      toolbarDivider: '#e6e6e6',
      iconButtonIcon: '#262626',
      iconButtonIconHover: '#d62976',
      chat: '#ffffff',
      chatText: '#262626',
      chatTextMuted: '#8e8e8e',
      chatUserBubble: 'linear-gradient(135deg, #fa7e1e, #d62976, #962fbf)',
      chatUserBubbleText: '#ffffff',
      chatUserBubbleBorder: 'transparent',
      chatAiBubble: '#efefef',
      chatAiText: '#262626',
      chatAiBubbleBorder: 'transparent',
      chatInput: '#ffffff',
      chatInputText: '#262626',
      chatInputBorder: '#dbdbdb',
      chatInputBorderFocus: '#d62976',
      chatSendButton: '#d62976',
      chatSendButtonIcon: '#ffffff',
      primaryButton: '#d62976',
      primaryButtonText: '#ffffff',
      primaryButtonBorder: '#d62976',
      gardenCard: '#ffffff',
      gardenCardHover: '#ffffff',
      gardenCardBorder: '#e6e6e6',
      gardenCardBorderHover: '#d62976',
      gardenCardTitle: '#000000',
      gardenCardText: '#555555',
      gardenCardMeta: '#8e8e8e',
      gardenCardThumbnail: '#efefef',
      gardenCardAspect: '1 / 1',
      gardenCardMinWidth: '200px',
      gardenGridGap: '20px',
      growthCard: '#ffffff',
      growthCardText: '#262626',
      growthCardTextMuted: '#8e8e8e',
      growthCardLabel: '#d62976',
      growthDotActive: '#d62976',
      growthCardAspect: '1 / 1',
      overlayBadge: 'rgba(255, 255, 255, 0.85)',
      overlayBadgeText: '#262626',
      fileTree: '#ffffff',
      fileTreeItemText: '#262626',
      fileTreeItemIcon: '#8e8e8e',
      fileTreeItemHover: '#f2f2f2',
      fileTreeItemSelected: '#fde3ee',
      fileTreeItemTextSelected: '#d62976',
      editorBackground: '#ffffff',
      syntaxComment: '#8e8e8e',
      syntaxKeyword: '#962fbf',
      syntaxString: '#d62976',
      syntaxNumber: '#fa7e1e',
      syntaxType: '#4f5bd5',
      syntaxFunction: '#262626',
      syntaxPunctuation: '#8e8e8e',
      syntaxVariable: '#262626',
      syntaxTag: '#962fbf',
      syntaxAttribute: '#d62976',
      bloomBg1: '#fafafa',
      bloomBg2: '#ffffff',
      bloom1: '#ffe9d6',
      bloom2: '#fde3ee',
      bloom3: '#ece6fb',
      bloom4: '#fafafa',
      bloom5: '#fff3e0',
      bloom6: '#e8ecff',
      bloomOpacity: '0.8',
      bloomBlur: '120px',
      ...uniformPanes({
        body: '#ffffff',
        surface: '#f2f2f2',
        border: 'linear-gradient(45deg, #feda75, #fa7e1e, #d62976, #962fbf, #4f5bd5)',
        header: 'linear-gradient(90deg, #feda75, #fa7e1e, #d62976, #962fbf, #4f5bd5)',
        headerText: '#ffffff',
        text: '#262626',
        textMuted: '#8e8e8e',
        caption: '#8e8e8e',
        heading: '#000000',
        accent: '#d62976',
        radius: '20px',
        headerRadius: '999px',
      }),
    },
  },

  // Homepage '97 — a GeoCities page: hot colors, Comic Sans, blue links.
  {
    id: 'homepage-97',
    name: "Homepage '97",
    section: 'Light',
    overrides: {
      bg: '#ffffcc',
      panel: '#ffffff',
      surface: '#ffff99',
      surfaceSolid: '#ffffff',
      accent: '#0000ee',
      accentMuted: '#ccccff',
      border: '#ff00ff',
      text: '#000000',
      textMuted: '#551a8b',
      heading: '#ff0000',
      caption: '#008000',
      highlight: '#ffff00',
      link: '#0000ee',
      linkVisited: '#551a8b',
      error: '#ff0000',
      warning: '#ff8800',
      success: '#008000',
      radius: '0px',
      radiusSm: '0px',
      paneGap: '12px',
      workspacePadding: '12px',
      paneBorderWidth: '4px',
      paneHeaderHeight: '34px',
      paneHeaderRadius: '0px',
      paneHeaderLabelFont: 'var(--font-display)',
      paneHeaderLabelSize: '16px',
      paneHeaderLabelWeight: '700',
      paneHeaderLabelCase: 'none',
      paneHeaderLabelTracking: '0',
      fontDisplay: "'Comic Sans MS', 'Comic Sans', 'Chalkboard SE', cursive",
      fontBody: 'Verdana, Geneva, sans-serif',
      fontMono: "'Courier New', Courier, monospace",
      elevationPanel: '6px 6px 0 #000000',
      elevationCard: '4px 4px 0 #000000',
      elevationCardHover: '8px 8px 0 #ff00ff',
      elevationModal: '10px 10px 0 #000000',
      scrim:
        'repeating-linear-gradient(45deg, rgb(0 0 0 / 0.6) 0 10px, rgb(0 0 0 / 0.75) 10px 20px)',
      motionScale: '0',
      toolbar: '#000080',
      toolbarText: '#ffff00',
      toolbarTextMuted: '#00ffff',
      toolbarBorder: '#ff00ff',
      toolbarDivider: '#ff00ff',
      iconButtonIcon: '#ffff00',
      iconButtonIconHover: '#ff00ff',
      iconButtonHover: '#000000',
      chat: '#ffffff',
      chatText: '#000000',
      chatTextMuted: '#551a8b',
      chatUserBubble: '#00ffff',
      chatUserBubbleText: '#000000',
      chatUserBubbleBorder: '#000000',
      chatAiBubble: '#ffff99',
      chatAiText: '#000000',
      chatAiBubbleBorder: '#000000',
      chatInput: '#ffffff',
      chatInputText: '#000000',
      chatInputBorder: '#000000',
      chatInputBorderFocus: '#ff00ff',
      chatInputPlaceholder: '#808080',
      chatSendButton: '#ff00ff',
      chatSendButtonHover: '#ff66ff',
      chatSendButtonIcon: '#ffffff',
      primaryButton: '#c0c0c0',
      primaryButtonText: '#000000',
      primaryButtonBorder: '#000000',
      actionButton: '#ffffff',
      actionButtonText: '#0000ee',
      actionButtonBorder: '#000000',
      gardenCard: '#ffffff',
      gardenCardHover: '#ffff99',
      gardenCardBorder: '#000000',
      gardenCardBorderHover: '#ff00ff',
      gardenCardTitle: '#ff0000',
      gardenCardText: '#000000',
      gardenCardMeta: '#551a8b',
      gardenCardThumbnail: '#000080',
      growthCard: '#ffffff',
      growthCardText: '#000000',
      growthCardTextMuted: '#551a8b',
      growthCardLabel: '#ff0000',
      growthDotActive: '#ff00ff',
      overlayBadge: '#ffff00',
      overlayBadgeText: '#000000',
      fileTree: '#ffffff',
      fileTreeItemText: '#0000ee',
      fileTreeItemIcon: '#000000',
      fileTreeItemHover: '#ffff99',
      fileTreeItemSelected: '#000080',
      fileTreeItemTextSelected: '#ffff00',
      editorBackground: '#ffffff',
      syntaxComment: '#008000',
      syntaxKeyword: '#0000ee',
      syntaxString: '#ff0000',
      syntaxNumber: '#ff00ff',
      syntaxType: '#551a8b',
      syntaxFunction: '#000000',
      syntaxPunctuation: '#000000',
      syntaxVariable: '#000000',
      syntaxTag: '#800000',
      syntaxAttribute: '#ff0000',
      ...NO_BLOOM,
      bloomBg1: '#ffffcc',
      bloomBg2: '#ffffcc',
      ...uniformPanes({
        body: '#ffffff',
        surface: '#ffff99',
        border:
          'repeating-linear-gradient(90deg, #ff0000 0 12px, #ff8800 12px 24px, #ffff00 24px 36px, #008000 36px 48px, #0000ff 48px 60px, #4b0082 60px 72px, #ff00ff 72px 84px)',
        header: '#000080',
        headerText: '#ffff00',
        text: '#000000',
        textMuted: '#551a8b',
        caption: '#008000',
        heading: '#ff0000',
        accent: '#0000ee',
        radius: '0px',
        headerRadius: '0px',
      }),
    },
  },

  // Ledger — subdued professional, light: warm paper, charcoal, one navy.
  {
    id: 'ledger',
    name: 'Ledger',
    section: 'Light',
    overrides: {
      bg: '#f6f4ef',
      panel: '#ffffff',
      surface: '#f1eee7',
      surfaceSolid: '#ffffff',
      accent: '#1f3a5f',
      accentMuted: '#e3e9f2',
      border: '#ddd8cd',
      text: '#232323',
      textMuted: '#6d6a63',
      heading: '#141414',
      caption: '#6d6a63',
      error: '#b3261e',
      warning: '#9a6b00',
      success: '#2e6b3a',
      radius: '3px',
      radiusSm: '2px',
      paneGap: '8px',
      workspacePadding: '8px',
      paneBorderWidth: '1px',
      paneHeaderHeight: '30px',
      paneHeaderLabelFont: 'var(--font-display)',
      paneHeaderLabelCase: 'none',
      paneHeaderLabelSize: '13px',
      paneHeaderLabelWeight: '600',
      paneHeaderLabelTracking: '0',
      fontDisplay: "Georgia, 'Times New Roman', serif",
      fontBody: "-apple-system, 'Segoe UI', Inter, system-ui, sans-serif",
      lineHeightBody: '1.5',
      elevationPanel: '0 1px 0 #ddd8cd',
      elevationCardHover: '0 4px 14px rgb(0 0 0 / 0.08)',
      scrim: 'rgb(35 35 35 / 0.45)',
      motionScale: '0.6',
      toolbar: '#ffffff',
      toolbarText: '#232323',
      toolbarTextMuted: '#6d6a63',
      toolbarBorder: '#ddd8cd',
      toolbarDivider: '#ddd8cd',
      iconButtonIcon: '#6d6a63',
      iconButtonIconHover: '#1f3a5f',
      chat: '#ffffff',
      chatText: '#232323',
      chatTextMuted: '#6d6a63',
      chatUserBubble: '#1f3a5f',
      chatUserBubbleText: '#ffffff',
      chatUserBubbleBorder: '#1f3a5f',
      chatAiBubble: '#f1eee7',
      chatAiText: '#232323',
      chatAiBubbleBorder: '#ddd8cd',
      chatInput: '#ffffff',
      chatInputText: '#232323',
      chatInputBorder: '#ddd8cd',
      chatInputBorderFocus: '#1f3a5f',
      chatSendButton: '#1f3a5f',
      chatSendButtonIcon: '#ffffff',
      primaryButton: '#1f3a5f',
      primaryButtonText: '#ffffff',
      gardenCard: '#ffffff',
      gardenCardHover: '#ffffff',
      gardenCardBorder: '#ddd8cd',
      gardenCardBorderHover: '#1f3a5f',
      gardenCardTitle: '#141414',
      gardenCardText: '#4a4842',
      gardenCardMeta: '#6d6a63',
      gardenCardThumbnail: '#f1eee7',
      gardenCardAspect: '3 / 2',
      growthCard: '#ffffff',
      growthCardText: '#232323',
      growthCardTextMuted: '#6d6a63',
      growthCardLabel: '#1f3a5f',
      growthDotActive: '#1f3a5f',
      overlayBadge: 'rgba(255, 255, 255, 0.9)',
      overlayBadgeText: '#232323',
      fileTree: '#ffffff',
      fileTreeItemText: '#232323',
      fileTreeItemIcon: '#6d6a63',
      fileTreeItemHover: '#f1eee7',
      fileTreeItemSelected: '#e3e9f2',
      fileTreeItemTextSelected: '#1f3a5f',
      editorBackground: '#ffffff',
      ...LIGHT_SYNTAX,
      ...NO_BLOOM,
      ...uniformPanes({
        body: '#ffffff',
        surface: '#f1eee7',
        border: '#ddd8cd',
        header: '#ffffff',
        headerText: '#141414',
        headerBorder: '#ddd8cd',
        text: '#232323',
        textMuted: '#6d6a63',
        caption: '#6d6a63',
        heading: '#141414',
        accent: '#1f3a5f',
        radius: '3px',
        headerRadius: '0px',
      }),
    },
  },

  // Almanac — vintage paper: cream, ink, a red rubric, double rules.
  {
    id: 'almanac',
    name: 'Almanac',
    section: 'Light',
    overrides: {
      bg: '#efe6d2',
      panel: '#f7f0df',
      surface: '#eee4cd',
      surfaceSolid: '#f7f0df',
      accent: '#a3422a',
      accentMuted: '#f0d9cf',
      border: '#7a6a52',
      text: '#2b2118',
      textMuted: '#6e5f4c',
      heading: '#2b2118',
      caption: '#a3422a',
      error: '#a3422a',
      warning: '#8a6a1a',
      success: '#4c6b3a',
      radius: '2px',
      radiusSm: '0px',
      paneGap: '18px',
      workspacePadding: '18px',
      paneBorderWidth: '5px',
      paneHeaderHeight: '34px',
      paneHeaderRadius: '0px',
      paneHeaderLabelFont: 'var(--font-display)',
      paneHeaderLabelSize: '15px',
      paneHeaderLabelWeight: '600',
      paneHeaderLabelCase: 'uppercase',
      paneHeaderLabelTracking: '0.2em',
      paneHeaderJustify: 'center',
      paneHeaderIconDisplay: 'none',
      fontDisplay: "'Cormorant Garamond', Georgia, serif",
      fontBody: "Georgia, 'Times New Roman', serif",
      fontMono: "'Courier New', Courier, monospace",
      lineHeightBody: '1.6',
      letterSpacingDisplay: '0.02em',
      elevationPanel: 'none',
      elevationCardHover: '0 0 0 1px #7a6a52',
      scrim: 'rgb(43 33 24 / 0.55)',
      motionScale: '0.5',
      toolbar: '#efe6d2',
      toolbarText: '#2b2118',
      toolbarTextMuted: '#6e5f4c',
      toolbarBorder: '#7a6a52',
      toolbarDivider: '#7a6a52',
      iconButtonIcon: '#6e5f4c',
      iconButtonIconHover: '#a3422a',
      chat: '#f7f0df',
      chatText: '#2b2118',
      chatTextMuted: '#6e5f4c',
      chatUserBubble: '#2b2118',
      chatUserBubbleText: '#f7f0df',
      chatUserBubbleBorder: '#2b2118',
      chatAiBubble: '#eee4cd',
      chatAiText: '#2b2118',
      chatAiBubbleBorder: '#7a6a52',
      chatInput: '#fffaf0',
      chatInputText: '#2b2118',
      chatInputBorder: '#7a6a52',
      chatInputBorderFocus: '#a3422a',
      chatSendButton: '#a3422a',
      chatSendButtonIcon: '#f7f0df',
      primaryButton: '#2b2118',
      primaryButtonText: '#f7f0df',
      primaryButtonBorder: '#2b2118',
      gardenCard: '#f7f0df',
      gardenCardHover: '#fffaf0',
      gardenCardBorder: '#7a6a52',
      gardenCardBorderHover: '#a3422a',
      gardenCardTitle: '#2b2118',
      gardenCardText: '#4a3f33',
      gardenCardMeta: '#6e5f4c',
      gardenCardThumbnail: '#e4d8bf',
      gardenCardAspect: '4 / 3',
      growthCard: '#f7f0df',
      growthCardText: '#2b2118',
      growthCardTextMuted: '#6e5f4c',
      growthCardLabel: '#a3422a',
      growthDotActive: '#a3422a',
      overlayBadge: '#2b2118',
      overlayBadgeText: '#f7f0df',
      fileTree: '#f7f0df',
      fileTreeItemText: '#2b2118',
      fileTreeItemIcon: '#6e5f4c',
      fileTreeItemHover: '#eee4cd',
      fileTreeItemSelected: '#2b2118',
      fileTreeItemTextSelected: '#f7f0df',
      editorBackground: '#fffaf0',
      syntaxComment: '#8a7a62',
      syntaxKeyword: '#a3422a',
      syntaxString: '#4c6b3a',
      syntaxNumber: '#8a6a1a',
      syntaxType: '#2b2118',
      syntaxFunction: '#2b2118',
      syntaxPunctuation: '#6e5f4c',
      syntaxVariable: '#2b2118',
      syntaxTag: '#a3422a',
      syntaxAttribute: '#8a6a1a',
      ...NO_BLOOM,
      bloomBg1: '#efe6d2',
      bloomBg2: '#efe6d2',
      ...uniformPanes({
        body: '#f7f0df',
        surface: '#eee4cd',
        // a double rule: ink, paper, ink
        border:
          'repeating-linear-gradient(0deg, #7a6a52 0 1px, #f7f0df 1px 3px, #7a6a52 3px 4px, #f7f0df 4px 5px)',
        header: '#f7f0df',
        headerText: '#2b2118',
        headerBorder: '#7a6a52',
        text: '#2b2118',
        textMuted: '#6e5f4c',
        caption: '#a3422a',
        heading: '#2b2118',
        accent: '#a3422a',
        radius: '2px',
        headerRadius: '0px',
      }),
    },
  },

  // Linen — Scandinavian minimal: white, air, one mint, very round.
  {
    id: 'linen',
    name: 'Linen',
    section: 'Light',
    overrides: {
      bg: '#f4f4f2',
      panel: '#ffffff',
      surface: '#f4f4f2',
      surfaceSolid: '#ffffff',
      accent: '#3aa17e',
      accentMuted: '#e2f3ec',
      border: '#e9e9e6',
      text: '#1c1c1c',
      textMuted: '#8a8a86',
      heading: '#111111',
      caption: '#8a8a86',
      error: '#d64545',
      warning: '#c98a00',
      success: '#3aa17e',
      radius: '24px',
      radiusSm: '14px',
      radiusLg: '32px',
      paneGap: '20px',
      workspacePadding: '20px',
      paneBorderWidth: '0px',
      paneHeaderHeight: '40px',
      paneHeaderRadius: '18px',
      paneHeaderLabelFont: 'var(--font-body)',
      paneHeaderLabelCase: 'none',
      paneHeaderLabelSize: '13px',
      paneHeaderLabelWeight: '500',
      paneHeaderLabelTracking: '0',
      fontDisplay: "'Outfit', -apple-system, sans-serif",
      fontBody: "'Outfit', -apple-system, sans-serif",
      density: '1.15',
      lineHeightBody: '1.6',
      elevationPanel: '0 8px 30px rgb(0 0 0 / 0.05)',
      elevationCard: '0 8px 30px rgb(0 0 0 / 0.05)',
      elevationCardHover: '0 16px 40px rgb(0 0 0 / 0.09)',
      elevationModal: '0 30px 80px rgb(0 0 0 / 0.15)',
      scrim: 'rgb(244 244 242 / 0.7)',
      motionScale: '1.4',
      toolbar: '#f4f4f2',
      toolbarText: '#1c1c1c',
      toolbarTextMuted: '#8a8a86',
      toolbarBorder: 'transparent',
      toolbarDivider: '#e9e9e6',
      iconButtonIcon: '#8a8a86',
      iconButtonIconHover: '#3aa17e',
      chat: '#ffffff',
      chatText: '#1c1c1c',
      chatTextMuted: '#8a8a86',
      chatUserBubble: '#1c1c1c',
      chatUserBubbleText: '#ffffff',
      chatUserBubbleBorder: '#1c1c1c',
      chatAiBubble: '#f4f4f2',
      chatAiText: '#1c1c1c',
      chatAiBubbleBorder: 'transparent',
      chatInput: '#f4f4f2',
      chatInputText: '#1c1c1c',
      chatInputBorder: 'transparent',
      chatInputBorderFocus: '#3aa17e',
      chatSendButton: '#1c1c1c',
      chatSendButtonIcon: '#ffffff',
      primaryButton: '#1c1c1c',
      primaryButtonText: '#ffffff',
      gardenCard: '#ffffff',
      gardenCardHover: '#ffffff',
      gardenCardBorder: 'transparent',
      gardenCardBorderHover: '#3aa17e',
      gardenCardTitle: '#111111',
      gardenCardText: '#5a5a57',
      gardenCardMeta: '#8a8a86',
      gardenCardThumbnail: '#ececea',
      gardenCardMinWidth: '260px',
      gardenGridGap: '24px',
      growthCard: '#ffffff',
      growthCardText: '#1c1c1c',
      growthCardTextMuted: '#8a8a86',
      growthCardLabel: '#3aa17e',
      growthDotActive: '#3aa17e',
      overlayBadge: 'rgba(255, 255, 255, 0.9)',
      overlayBadgeText: '#1c1c1c',
      fileTree: '#ffffff',
      fileTreeItemText: '#1c1c1c',
      fileTreeItemIcon: '#8a8a86',
      fileTreeItemHover: '#f4f4f2',
      fileTreeItemSelected: '#e2f3ec',
      fileTreeItemTextSelected: '#1c1c1c',
      editorBackground: '#ffffff',
      ...LIGHT_SYNTAX,
      bloomBg1: '#f4f4f2',
      bloomBg2: '#ffffff',
      bloom1: '#e2f3ec',
      bloom2: '#f4f4f2',
      bloom3: '#ececea',
      bloom4: '#ffffff',
      bloom5: '#e8f0ec',
      bloom6: '#f4f4f2',
      bloomOpacity: '0.6',
      bloomBlur: '140px',
      ...uniformPanes({
        body: '#ffffff',
        surface: '#f4f4f2',
        border: 'transparent',
        header: '#ffffff',
        headerText: '#1c1c1c',
        text: '#1c1c1c',
        textMuted: '#8a8a86',
        caption: '#8a8a86',
        heading: '#111111',
        accent: '#3aa17e',
        radius: '24px',
        headerRadius: '18px',
        borderWidth: '0px',
      }),
    },
  },

  // Sherbet — playful pastels: each pane its own scoop.
  {
    id: 'sherbet',
    name: 'Sherbet',
    section: 'Light',
    overrides: {
      bg: '#f3efff',
      panel: '#ffffff',
      surface: '#f7f4ff',
      surfaceSolid: '#ffffff',
      accent: '#7c5cff',
      accentMuted: '#e9e3ff',
      border: '#e6dfff',
      text: '#2a2540',
      textMuted: '#8a83a8',
      heading: '#2a2540',
      caption: '#7c5cff',
      error: '#ff5c8a',
      warning: '#ffb84d',
      success: '#4cd4a2',
      radius: '18px',
      radiusSm: '10px',
      paneGap: '14px',
      workspacePadding: '14px',
      paneBorderWidth: '3px',
      paneHeaderHeight: '34px',
      paneHeaderRadius: '12px',
      paneHeaderLabelFont: 'var(--font-body)',
      paneHeaderLabelCase: 'none',
      paneHeaderLabelSize: '13px',
      paneHeaderLabelWeight: '700',
      paneHeaderLabelTracking: '0',
      fontDisplay: "'Outfit', -apple-system, sans-serif",
      fontBody: "'Outfit', -apple-system, sans-serif",
      density: '1.05',
      elevationPanel: '0 6px 20px rgb(124 92 255 / 0.08)',
      elevationCardHover: '0 14px 30px rgb(124 92 255 / 0.15)',
      scrim: 'rgb(42 37 64 / 0.5)',
      toolbar: '#ffffff',
      toolbarText: '#2a2540',
      toolbarTextMuted: '#8a83a8',
      toolbarBorder: '#e6dfff',
      toolbarDivider: '#e6dfff',
      iconButtonIcon: '#8a83a8',
      iconButtonIconHover: '#7c5cff',
      chat: '#ffffff',
      chatText: '#2a2540',
      chatTextMuted: '#8a83a8',
      chatUserBubble: '#ffd6e7',
      chatUserBubbleText: '#2a2540',
      chatUserBubbleBorder: 'transparent',
      chatAiBubble: '#e9e3ff',
      chatAiText: '#2a2540',
      chatAiBubbleBorder: 'transparent',
      chatInput: '#f7f4ff',
      chatInputText: '#2a2540',
      chatInputBorder: '#e6dfff',
      chatInputBorderFocus: '#7c5cff',
      chatSendButton: '#7c5cff',
      chatSendButtonIcon: '#ffffff',
      primaryButton: '#7c5cff',
      primaryButtonText: '#ffffff',
      gardenCard: '#ffffff',
      gardenCardHover: '#ffffff',
      gardenCardBorder: '#e6dfff',
      gardenCardBorderHover: '#7c5cff',
      gardenCardTitle: '#2a2540',
      gardenCardText: '#5f5880',
      gardenCardMeta: '#8a83a8',
      gardenCardThumbnail: '#e9e3ff',
      growthCard: '#ffffff',
      growthCardText: '#2a2540',
      growthCardTextMuted: '#8a83a8',
      growthCardLabel: '#7c5cff',
      growthDotActive: '#7c5cff',
      overlayBadge: 'rgba(255, 255, 255, 0.9)',
      overlayBadgeText: '#2a2540',
      fileTree: '#ffffff',
      fileTreeItemText: '#2a2540',
      fileTreeItemIcon: '#8a83a8',
      fileTreeItemHover: '#f7f4ff',
      fileTreeItemSelected: '#e9e3ff',
      fileTreeItemTextSelected: '#7c5cff',
      editorBackground: '#ffffff',
      ...LIGHT_SYNTAX,
      bloomBg1: '#f3efff',
      bloomBg2: '#ffffff',
      bloom1: '#ffd6e7',
      bloom2: '#e9e3ff',
      bloom3: '#d6f5ff',
      bloom4: '#fff1d6',
      bloom5: '#d9fff0',
      bloom6: '#f3efff',
      bloomOpacity: '0.9',
      bloomBlur: '110px',
      ...uniformPanes({
        body: '#ffffff',
        surface: '#f7f4ff',
        border: '#ffffff',
        header: '#e9e3ff',
        headerText: '#2a2540',
        text: '#2a2540',
        textMuted: '#8a83a8',
        heading: '#2a2540',
        accent: '#7c5cff',
        radius: '18px',
        headerRadius: '12px',
      }),
      ...tintedHeaders(
        [
          '#ffd6e7',
          '#ffe3c2',
          '#fff4b8',
          '#d9fff0',
          '#d6f5ff',
          '#e9e3ff',
          '#f5d6ff',
          '#ffd6d6',
          '#e3ffd6',
        ],
        '#2a2540',
      ),
    },
  },

  // Pretty in Pink — a John Hughes prom: blush, rose, mint and lavender,
  // a brush-script title card, soft everything.
  {
    id: 'pretty-in-pink',
    name: 'Pretty in Pink',
    section: 'Light',
    overrides: {
      bg: '#f9e4ec',
      panel: '#fff6f9',
      surface: '#fbe9f0',
      surfaceSolid: '#fff6f9',
      accent: '#d4457a',
      accentMuted: '#fbd3e1',
      border: '#e8a0bf',
      text: '#3b2530',
      textMuted: '#9a6f84',
      heading: '#c2185b',
      caption: '#7fb8ad',
      highlight: '#b9a6e0',
      error: '#d4457a',
      warning: '#e0a15a',
      success: '#7fd1c1',
      radius: '14px',
      radiusSm: '8px',
      radiusLg: '22px',
      paneGap: '12px',
      workspacePadding: '12px',
      paneBorderWidth: '2px',
      paneHeaderHeight: '38px',
      paneHeaderRadius: '10px',
      paneHeaderLabelFont: 'var(--font-display)',
      paneHeaderLabelSize: '18px',
      paneHeaderLabelWeight: '400',
      paneHeaderLabelCase: 'none',
      paneHeaderLabelTracking: '0.01em',
      fontDisplay: "'Snell Roundhand', 'Brush Script MT', 'Segoe Script', cursive",
      fontBody: "'Helvetica Neue', Helvetica, Arial, sans-serif",
      letterSpacingBody: '0.01em',
      lineHeightBody: '1.55',
      elevationPanel: '0 8px 24px rgb(212 69 122 / 0.10)',
      elevationCard: '0 4px 14px rgb(212 69 122 / 0.08)',
      elevationCardHover: '0 16px 34px rgb(212 69 122 / 0.18)',
      elevationModal: '0 30px 80px rgb(59 37 48 / 0.35)',
      scrim: 'rgb(59 37 48 / 0.45)',
      motionScale: '1.3',
      toolbar: '#fff6f9',
      toolbarText: '#3b2530',
      toolbarTextMuted: '#9a6f84',
      toolbarBorder: '#f3c7d8',
      toolbarDivider: '#f3c7d8',
      iconButtonIcon: '#9a6f84',
      iconButtonIconHover: '#d4457a',
      chat: '#fff6f9',
      chatText: '#3b2530',
      chatTextMuted: '#9a6f84',
      chatUserBubble: 'linear-gradient(135deg, #f7a8c8, #d4457a)',
      chatUserBubbleText: '#ffffff',
      chatUserBubbleBorder: 'transparent',
      chatAiBubble: '#e6f7f3',
      chatAiText: '#2f4a45',
      chatAiBubbleBorder: '#bfe8df',
      chatInput: '#ffffff',
      chatInputText: '#3b2530',
      chatInputBorder: '#e8a0bf',
      chatInputBorderFocus: '#d4457a',
      chatInputPlaceholder: '#c58aa5',
      chatSendButton: '#d4457a',
      chatSendButtonHover: '#e0608f',
      chatSendButtonIcon: '#ffffff',
      primaryButton: '#d4457a',
      primaryButtonText: '#ffffff',
      primaryButtonBorder: '#d4457a',
      actionButton: '#fbe9f0',
      actionButtonText: '#c2185b',
      actionButtonBorder: '#e8a0bf',
      gardenCard: '#fff6f9',
      gardenCardHover: '#ffffff',
      gardenCardBorder: '#f3c7d8',
      gardenCardBorderHover: '#d4457a',
      gardenCardTitle: '#c2185b',
      gardenCardText: '#6b4a5a',
      gardenCardMeta: '#9a6f84',
      gardenCardThumbnail: '#fbd3e1',
      gardenCardAspect: '4 / 3',
      growthCard: '#fff6f9',
      growthCardHover: '#ffffff',
      growthCardActive: '#fbd3e1',
      growthCardText: '#3b2530',
      growthCardTextMuted: '#9a6f84',
      growthCardLabel: '#d4457a',
      growthDotActive: '#d4457a',
      overlayBadge: 'rgba(255, 246, 249, 0.9)',
      overlayBadgeText: '#c2185b',
      fileTree: '#fff6f9',
      fileTreeItemText: '#3b2530',
      fileTreeItemIcon: '#9a6f84',
      fileTreeItemHover: '#fbe9f0',
      fileTreeItemSelected: '#fbd3e1',
      fileTreeItemTextSelected: '#c2185b',
      editorBackground: '#ffffff',
      syntaxComment: '#b08aa0',
      syntaxKeyword: '#c2185b',
      syntaxString: '#3f9e8f',
      syntaxNumber: '#8a63d2',
      syntaxType: '#8a63d2',
      syntaxFunction: '#3b2530',
      syntaxPunctuation: '#9a6f84',
      syntaxVariable: '#3b2530',
      syntaxTag: '#c2185b',
      syntaxAttribute: '#3f9e8f',
      bloomBg1: '#f9e4ec',
      bloomBg2: '#fff6f9',
      bloom1: '#f7a8c8',
      bloom2: '#bfe8df',
      bloom3: '#d9cff3',
      bloom4: '#fbd3e1',
      bloom5: '#fff1d6',
      bloom6: '#f9e4ec',
      bloomOpacity: '0.85',
      bloomBlur: '110px',
      ...uniformPanes({
        body: '#fff6f9',
        surface: '#fbe9f0',
        border: 'linear-gradient(160deg, #f7a8c8, #b9a6e0 55%, #7fd1c1)',
        header: 'linear-gradient(90deg, #f7a8c8, #e8a0bf 60%, #d9cff3)',
        headerText: '#6b1e3d',
        text: '#3b2530',
        textMuted: '#9a6f84',
        caption: '#7fb8ad',
        heading: '#c2185b',
        accent: '#d4457a',
        radius: '14px',
        headerRadius: '10px',
      }),
    },
  },

  // Windows 95 — teal desktop, grey windows, navy title bars, bevels, no radius.
  {
    id: 'windows-95',
    name: 'Windows 95',
    section: 'Light',
    overrides: {
      bg: '#008080',
      panel: '#c0c0c0',
      surface: '#dfdfdf',
      surfaceSolid: '#c0c0c0',
      accent: '#000080',
      accentMuted: '#b8b8d8',
      border: '#808080',
      text: '#000000',
      textMuted: '#3a3a3a',
      heading: '#000000',
      caption: '#000080',
      title: '#000000',
      highlight: '#000080',
      error: '#c00000',
      warning: '#a06000',
      success: '#008000',
      radius: '0px',
      radiusSm: '0px',
      radiusLg: '0px',
      paneGap: '6px',
      workspacePadding: '6px',
      paneBorderWidth: '3px',
      paneHeaderHeight: '22px',
      paneHeaderRadius: '0px',
      paneHeaderPadding: '3px',
      fontDisplay: "Tahoma, 'MS Sans Serif', Verdana, sans-serif",
      fontBody: "Tahoma, 'MS Sans Serif', Verdana, sans-serif",
      fontMono: "'Courier New', Courier, monospace",
      // Taskbar
      toolbar: '#c0c0c0',
      toolbarText: '#000000',
      toolbarTextMuted: '#3a3a3a',
      toolbarBorder: '#ffffff',
      toolbarDivider: '#808080',
      iconButtonIcon: '#000000',
      iconButtonIconHover: '#000080',
      iconButtonHover: '#dfdfdf',
      iconButtonBorder: '#808080',
      // Chat: a dialog box
      chat: '#c0c0c0',
      chatText: '#000000',
      chatTextMuted: '#3a3a3a',
      chatBorder: '#808080',
      chatUserBubble: '#000080',
      chatUserBubbleText: '#ffffff',
      chatUserBubbleBorder: '#000080',
      chatAiBubble: '#ffffff',
      chatAiText: '#000000',
      chatAiBubbleBorder: '#808080',
      chatInput: '#ffffff',
      chatInputText: '#000000',
      chatInputBorder: '#808080',
      chatInputBorderFocus: '#000080',
      chatInputPlaceholder: '#808080',
      chatSendButton: '#c0c0c0',
      chatSendButtonHover: '#dfdfdf',
      chatSendButtonIcon: '#000000',
      // Controls
      primaryButton: '#c0c0c0',
      primaryButtonText: '#000000',
      primaryButtonBorder: '#000000',
      actionButton: '#c0c0c0',
      actionButtonText: '#000000',
      actionButtonBorder: '#808080',
      badge: '#ffffff',
      badgeText: '#000080',
      badgeBorder: '#808080',
      toggle: '#ffffff',
      toggleActive: '#000080',
      toggleThumb: '#808080',
      toggleThumbActive: '#ffffff',
      toggleBorder: '#808080',
      // Cards: icons on the desktop
      gardenCard: '#c0c0c0',
      gardenCardHover: '#dfdfdf',
      gardenCardBorder: '#ffffff',
      gardenCardBorderHover: '#000080',
      gardenCardTitle: '#000000',
      gardenCardText: '#202020',
      gardenCardMeta: '#3a3a3a',
      gardenCardThumbnail: '#008080',
      growthCard: '#ffffff',
      growthCardHover: '#dfdfdf',
      growthCardActive: '#b8b8d8',
      growthCardText: '#000000',
      growthCardTextMuted: '#3a3a3a',
      growthCardLabel: '#000080',
      growthDot: '#808080',
      growthDotActive: '#000080',
      overlayBadge: '#000080',
      overlayBadgeText: '#ffffff',
      // Explorer
      fileTree: '#ffffff',
      fileTreeItemText: '#000000',
      fileTreeItemIcon: '#000000',
      fileTreeItemHover: '#dfdfdf',
      fileTreeItemSelected: '#000080',
      fileTreeItemTextSelected: '#ffffff',
      // Notepad
      editorBackground: '#ffffff',
      codeBlock: '#ffffff',
      codeBlockText: '#000000',
      codeBlockBorder: '#808080',
      syntaxComment: '#008000',
      syntaxKeyword: '#000080',
      syntaxString: '#800000',
      syntaxNumber: '#800080',
      syntaxType: '#000080',
      syntaxFunction: '#000000',
      syntaxPunctuation: '#000000',
      syntaxVariable: '#000000',
      syntaxTag: '#800000',
      syntaxAttribute: '#ff0000',
      // Desktop: flat teal, no bloom
      bloomBg1: '#008080',
      bloomBg2: '#008080',
      bloom1: '#008080',
      bloom2: '#008080',
      bloom3: '#008080',
      bloom4: '#008080',
      bloom5: '#008080',
      bloom6: '#008080',
      bloomOpacity: '0',
      ...win95Panes([
        'paneCollaboration',
        'paneArtifacts',
        'paneWorkshop',
        'paneDetails',
        'paneHistory',
        'paneExport',
        'paneSync',
        'panePublish',
        'paneStore',
      ]),
    },
  },

  // Ivory — neutral tint on parchment base
  {
    id: 'ivory',
    name: 'Ivory',
    section: 'Light',
    overrides: {
      ...LIGHT_SYNTAX,
      bg: '#F2F0EC',
      surface: '#EAE8E2',
      panel: '#E2E0DA',
      accent: '#47473d',
      border: '#c7c4ba',
      text: '#0f0f0a',
      textMuted: '#616153',
      accentMuted: 'rgba(80,80,72,0.12)',
      paneCollaboration: '#903424',
      paneArtifacts: '#77521e',
      paneWorkshop: '#515214',
      paneDetails: '#265f18',
      paneHistory: '#14524a',
      paneExport: '#1e4278',
      paneSync: '#352a6c',
      panePublish: '#7f203f',
      paneStore: '#523914',
      ...ghostPanes(
        {
          paneCollaboration: '#9E4030',
          paneArtifacts: '#8E6020',
          paneWorkshop: '#6E7010',
          paneDetails: '#307020',
          paneHistory: '#206058',
          paneExport: '#305080',
          paneSync: '#484070',
          panePublish: '#803850',
          paneStore: '#684818',
        },
        '#DAD8D0',
        '#6E6E64',
      ),
      bloom1: '#c8b898',
      bloom2: '#b0a898',
      bloom3: '#98b8a8',
      bloom4: '#c0b098',
      bloom5: '#b0b898',
      bloom6: '#98b8a8',
      bloomOpacity: '0.6',
    },
  },

  // Mist — blue tint on parchment base
  {
    id: 'mist',
    name: 'Mist',
    section: 'Light',
    overrides: {
      ...LIGHT_SYNTAX,
      bg: '#EEF0F4',
      surface: '#E4E8EE',
      panel: '#DAE0E8',
      accent: '#2a4d77',
      border: '#b8c1d1',
      text: '#060b14',
      textMuted: '#43596f',
      accentMuted: 'rgba(62,88,120,0.12)',
      paneCollaboration: '#903424',
      paneArtifacts: '#77521e',
      paneWorkshop: '#515214',
      paneDetails: '#265f18',
      paneHistory: '#14524a',
      paneExport: '#1e4278',
      paneSync: '#352a6c',
      panePublish: '#7f203f',
      paneStore: '#523914',
      ...ghostPanes(
        {
          paneCollaboration: '#9E4030',
          paneArtifacts: '#8E6020',
          paneWorkshop: '#6E7010',
          paneDetails: '#307020',
          paneHistory: '#206058',
          paneExport: '#305080',
          paneSync: '#484070',
          panePublish: '#803850',
          paneStore: '#684818',
        },
        '#D0D8E0',
        '#586878',
      ),
      bloom1: '#90a8c8',
      bloom2: '#a890b8',
      bloom3: '#80b0c0',
      bloom4: '#c0a0a8',
      bloom5: '#a0b0a0',
      bloom6: '#80b0b8',
      bloomOpacity: '0.6',
    },
  },

  // Sage — green tint on parchment base
  {
    id: 'sage',
    name: 'Sage',
    section: 'Light',
    overrides: {
      ...LIGHT_SYNTAX,
      bg: '#EEF2EC',
      surface: '#E4ECE0',
      panel: '#DAE4D4',
      accent: '#2e6526',
      border: '#bbc8b5',
      text: '#081105',
      textMuted: '#46663b',
      accentMuted: 'rgba(62,104,56,0.12)',
      paneCollaboration: '#903424',
      paneArtifacts: '#77521e',
      paneWorkshop: '#515214',
      paneDetails: '#265f18',
      paneHistory: '#14524a',
      paneExport: '#1e4278',
      paneSync: '#352a6c',
      panePublish: '#7f203f',
      paneStore: '#523914',
      ...ghostPanes(
        {
          paneCollaboration: '#9E4030',
          paneArtifacts: '#8E6020',
          paneWorkshop: '#6E7010',
          paneDetails: '#307020',
          paneHistory: '#206058',
          paneExport: '#305080',
          paneSync: '#484070',
          panePublish: '#803850',
          paneStore: '#684818',
        },
        '#D0DCC8',
        '#587050',
      ),
      bloom1: '#a8c890',
      bloom2: '#90b0b8',
      bloom3: '#80c8a0',
      bloom4: '#c0b090',
      bloom5: '#a0c080',
      bloom6: '#80c0a0',
      bloomOpacity: '0.6',
    },
  },

  // Rose — pink tint on parchment base
  {
    id: 'rose',
    name: 'Rose',
    section: 'Light',
    overrides: {
      ...LIGHT_SYNTAX,
      bg: '#F4EEEE',
      surface: '#ECE4E4',
      panel: '#E4DADC',
      accent: '#8a293f',
      border: '#c7baba',
      text: '#17070b',
      textMuted: '#6f434e',
      accentMuted: 'rgba(136,64,80,0.12)',
      paneCollaboration: '#903424',
      paneArtifacts: '#77521e',
      paneWorkshop: '#515214',
      paneDetails: '#265f18',
      paneHistory: '#14524a',
      paneExport: '#1e4278',
      paneSync: '#352a6c',
      panePublish: '#7f203f',
      paneStore: '#523914',
      ...ghostPanes(
        {
          paneCollaboration: '#9E4030',
          paneArtifacts: '#8E6020',
          paneWorkshop: '#6E7010',
          paneDetails: '#307020',
          paneHistory: '#206058',
          paneExport: '#305080',
          paneSync: '#484070',
          panePublish: '#803850',
          paneStore: '#684818',
        },
        '#DCD0D0',
        '#785860',
      ),
      bloom1: '#d89098',
      bloom2: '#c880a0',
      bloom3: '#90c0b0',
      bloom4: '#d0a098',
      bloom5: '#c0b890',
      bloom6: '#88b8a8',
      bloomOpacity: '0.6',
    },
  },

  // Parchment — warm cream/brown, the anchor light theme
  {
    id: 'parchment',
    name: 'Parchment',
    section: 'Light',
    overrides: {
      ...LIGHT_SYNTAX,
      bg: '#f4ece0',
      surface: '#ece2d4',
      panel: '#e4d8c8',
      accent: '#6e4513',
      border: '#ccbaa1',
      text: '#140e06',
      textMuted: '#664e2e',
      accentMuted: 'rgba(110,78,40,0.12)',
      paneCollaboration: '#903424',
      paneArtifacts: '#77521e',
      paneWorkshop: '#515214',
      paneDetails: '#265f18',
      paneHistory: '#14524a',
      paneExport: '#1e4278',
      paneSync: '#352a6c',
      panePublish: '#7f203f',
      paneStore: '#523914',
      ...ghostPanes(
        {
          paneCollaboration: '#9E4030',
          paneArtifacts: '#8E6020',
          paneWorkshop: '#6E7010',
          paneDetails: '#307020',
          paneHistory: '#206058',
          paneExport: '#305080',
          paneSync: '#484070',
          panePublish: '#803850',
          paneStore: '#684818',
        },
        '#ddd0c0',
        '#6E5C44',
      ),
      bloom1: '#e0a070',
      bloom2: '#c890b0',
      bloom3: '#80c8b8',
      bloom4: '#d89070',
      bloom5: '#b8b870',
      bloom6: '#70b8a0',
      bloomOpacity: '0.6',
    },
  },
];
