import { beforeEach, expect, it, vi } from 'vitest';
import { localApiFixture } from '@/test/local-api-fixture';
import { initServices, getServices } from '@/services';
import { includedImage } from '@/api/inference';
import { createToolExecutor } from './tools';
vi.mock('@/api/inference', async (original) => ({
  ...(await original<typeof import('@/api/inference')>()),
  includedImage: vi.fn(),
}));
localApiFixture();
const bytes = Uint8Array.from(
  Buffer.from(
    'iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAFElEQVR4nGNgmMDKwMDAxMDAwMAAAAwWAKUF4Je/AAAAAElFTkSuQmCC',
    'base64',
  ),
);
beforeEach(async () => {
  vi.restoreAllMocks();
  await initServices();
  vi.mocked(includedImage).mockResolvedValue({
    blob: new Blob([bytes], { type: 'image/png' }),
    requestId: crypto.randomUUID(),
  });
});
it('retains generated bytes when the requested save fails and passes the saved original into editing', async () => {
  const services = getServices();
  const crux = await services.crux.create({ title: 'Image recovery' });
  const upload = services.artifact.upload.bind(services.artifact);
  vi.spyOn(services.artifact, 'upload').mockImplementation(async (input) => {
    if (input.meta?.path === 'blocked.png') throw new Error('Path is occupied');
    return upload(input);
  });
  const run = createToolExecutor(crux.id, undefined, 'garden-included');
  const result = await run('generate_image', { prompt: 'A garden', path: 'blocked.png' });
  expect(result).toContain('Use the saved image; do not generate it again');
  const saved = (await services.artifact.findByResource('crux', crux.id))[0];
  if (!saved) throw new Error('Generated original was not retained');
  expect(saved.meta?.path).toMatch(/^images\/generated\//);
  expect(new Uint8Array(await (await services.artifact.downloadBlob(saved)).arrayBuffer())).toEqual(
    bytes,
  );
  await run('generate_image', {
    prompt: 'Lighter',
    path: 'edited.png',
    source_path: saved.meta?.path,
  });
  const reference = vi.mocked(includedImage).mock.calls.at(-1)![2]!;
  expect(new Uint8Array(await reference.arrayBuffer())).toEqual(bytes);
  expect(
    (await services.artifact.findByResource('crux', crux.id)).some(
      (a) => a.meta?.path === 'edited.png',
    ),
  ).toBe(true);
});
it('does not save or switch providers when included generation refuses', async () => {
  const services = getServices();
  const crux = await services.crux.create({ title: 'Image refusal' });
  vi.mocked(includedImage).mockRejectedValue(new Error('Included allowance reached'));
  const result = await createToolExecutor(
    crux.id,
    undefined,
    'garden-included',
  )('generate_image', { prompt: 'A garden', path: 'banner.png' });
  expect(result).toContain('Included allowance reached');
  expect(await services.artifact.findByResource('crux', crux.id)).toEqual([]);
});
it('explains a total local save failure without silently generating again', async () => {
  const services = getServices();
  const crux = await services.crux.create({ title: 'Disk refusal' });
  vi.spyOn(services.artifact, 'upload').mockRejectedValue(new Error('Disk full'));
  const before = vi.mocked(includedImage).mock.calls.length;
  const result = await createToolExecutor(
    crux.id,
    undefined,
    'garden-included',
  )('generate_image', { prompt: 'Garden', path: 'banner.png' });
  expect(result).toContain('Do not generate another image automatically');
  expect(vi.mocked(includedImage).mock.calls.length).toBe(before + 1);
  expect(await services.artifact.findByResource('crux', crux.id)).toEqual([]);
});

it('keeps generated image writes inside an exact task file scope', async () => {
  const services = getServices();
  const crux = await services.crux.create({ title: 'Scoped image' });
  const run = createToolExecutor(crux.id, undefined, 'garden-included', {
    scope: { paths: ['banner.png'] },
  });
  expect(await run('generate_image', { prompt: 'A garden', path: 'banner.png' })).toContain(
    'Generated and saved',
  );
  expect(
    (await services.artifact.findByResource('crux', crux.id)).map((a) => a.meta?.path),
  ).toEqual(['banner.png']);
});
