import { beforeEach, expect, it, vi } from 'vitest';
const fixture = vi.hoisted(() => ({
  generate: vi.fn(),
  settings: new Map(),
  put: vi.fn(),
  load: vi.fn(),
}));
vi.mock('./tools', () => ({ generateImageBlob: fixture.generate }));
vi.mock('@/services/settings', () => ({
  onSettingChange: () => () => {},
  getSetting: (key: string) => fixture.settings.get(key),
  setSetting: (key: string, value: string) => fixture.settings.set(key, value),
}));
vi.mock('@/services/blobs', () => ({ putBlob: fixture.put, blobObjectUrl: fixture.load }));
import { runThemeTool } from './theme-tools';
import { clearBackgroundImage } from '@/services/background';
import { useMoodStore } from '@/stores/moodStore';

beforeEach(async () => {
  await clearBackgroundImage();
  vi.clearAllMocks();
  fixture.settings.clear();
});

it('reports a superseded generation honestly and preserves the newer user choice', async () => {
  let finish!: (value: { blob: Blob; provider: string }) => void;
  fixture.generate.mockImplementation(
    () =>
      new Promise((resolve) => {
        finish = resolve;
      }),
  );
  const pending = runThemeTool('set_background', { prompt: 'a slow landscape' });
  await vi.waitFor(() => expect(finish).toBeTypeOf('function'));
  await runThemeTool('set_background', { type: 'blank' });
  finish({ blob: new Blob(['landscape']), provider: 'fixture' });
  expect(await pending).toContain('was not applied');
  expect(fixture.put).not.toHaveBeenCalled();
  expect(useMoodStore.getState().backgroundUrl).toBeNull();
});

it('saves successful generated bytes and reports the provider only after applying them', async () => {
  const blob = new Blob(['landscape']);
  fixture.generate.mockResolvedValue({ blob, provider: 'fixture' });
  fixture.put.mockResolvedValue('fingerprint');
  fixture.load.mockResolvedValue('blob:generated');
  expect(await runThemeTool('set_background', { prompt: 'landscape' })).toContain(
    'with fixture and set it',
  );
  expect(fixture.put).toHaveBeenCalledWith(blob);
  expect(useMoodStore.getState().backgroundUrl).toBe('blob:generated');
});
